// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from react.djinni

package com.youme.reactcpp;

public enum JavascriptType {
    NIL,
    BOOLEAN,
    NUMBER,
    STRING,
    ARRAY,
    MAP,
    ;
}
