// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

#pragma once

#include "RNYIMUserInfoManager.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeRNYIMUserInfoManager final : ::djinni::JniInterface<::RNYIMUserInfoManager, NativeRNYIMUserInfoManager> {
public:
    using CppType = std::shared_ptr<::RNYIMUserInfoManager>;
    using CppOptType = std::shared_ptr<::RNYIMUserInfoManager>;
    using JniType = jobject;

    using Boxed = NativeRNYIMUserInfoManager;

    ~NativeRNYIMUserInfoManager();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeRNYIMUserInfoManager>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeRNYIMUserInfoManager>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeRNYIMUserInfoManager();
    friend ::djinni::JniClass<NativeRNYIMUserInfoManager>;
    friend ::djinni::JniInterface<::RNYIMUserInfoManager, NativeRNYIMUserInfoManager>;

};

}  // namespace djinni_generated
