// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

#include "NativeRNYIMCommon.hpp"  // my header
#include "Marshal.hpp"
#include "NativeReactBridge.hpp"

namespace djinni_generated {

NativeRNYIMCommon::NativeRNYIMCommon() : ::djinni::JniInterface<::RNYIMCommon, NativeRNYIMCommon>("com/youme/imrn/jni/RNYIMCommon$CppProxy") {}

NativeRNYIMCommon::~NativeRNYIMCommon() = default;


CJNIEXPORT void JNICALL Java_com_youme_imrn_jni_RNYIMCommon_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::RNYIMCommon>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_youme_imrn_jni_RNYIMCommon_create(JNIEnv* jniEnv, jobject /*this*/, ::djinni_generated::NativeReactBridge::JniType j_bridge)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::RNYIMCommon::create(::djinni_generated::NativeReactBridge::toCpp(jniEnv, j_bridge));
        return ::djinni::release(::djinni_generated::NativeRNYIMCommon::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
