// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

#pragma once

#include "RNYIMLocationManager.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeRNYIMLocationManager final : ::djinni::JniInterface<::RNYIMLocationManager, NativeRNYIMLocationManager> {
public:
    using CppType = std::shared_ptr<::RNYIMLocationManager>;
    using CppOptType = std::shared_ptr<::RNYIMLocationManager>;
    using JniType = jobject;

    using Boxed = NativeRNYIMLocationManager;

    ~NativeRNYIMLocationManager();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeRNYIMLocationManager>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeRNYIMLocationManager>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeRNYIMLocationManager();
    friend ::djinni::JniClass<NativeRNYIMLocationManager>;
    friend ::djinni::JniInterface<::RNYIMLocationManager, NativeRNYIMLocationManager>;

};

}  // namespace djinni_generated
