// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

#pragma once

#include "RNYIMHistoryMessageManager.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeRNYIMHistoryMessageManager final : ::djinni::JniInterface<::RNYIMHistoryMessageManager, NativeRNYIMHistoryMessageManager> {
public:
    using CppType = std::shared_ptr<::RNYIMHistoryMessageManager>;
    using CppOptType = std::shared_ptr<::RNYIMHistoryMessageManager>;
    using JniType = jobject;

    using Boxed = NativeRNYIMHistoryMessageManager;

    ~NativeRNYIMHistoryMessageManager();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeRNYIMHistoryMessageManager>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeRNYIMHistoryMessageManager>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeRNYIMHistoryMessageManager();
    friend ::djinni::JniClass<NativeRNYIMHistoryMessageManager>;
    friend ::djinni::JniInterface<::RNYIMHistoryMessageManager, NativeRNYIMHistoryMessageManager>;

};

}  // namespace djinni_generated
