// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

#pragma once

#include "RNYIMMessageManager.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeRNYIMMessageManager final : ::djinni::JniInterface<::RNYIMMessageManager, NativeRNYIMMessageManager> {
public:
    using CppType = std::shared_ptr<::RNYIMMessageManager>;
    using CppOptType = std::shared_ptr<::RNYIMMessageManager>;
    using JniType = jobject;

    using Boxed = NativeRNYIMMessageManager;

    ~NativeRNYIMMessageManager();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeRNYIMMessageManager>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeRNYIMMessageManager>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeRNYIMMessageManager();
    friend ::djinni::JniClass<NativeRNYIMMessageManager>;
    friend ::djinni::JniInterface<::RNYIMMessageManager, NativeRNYIMMessageManager>;

};

}  // namespace djinni_generated
