// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

#pragma once

#include "RNYIMCommon.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeRNYIMCommon final : ::djinni::JniInterface<::RNYIMCommon, NativeRNYIMCommon> {
public:
    using CppType = std::shared_ptr<::RNYIMCommon>;
    using CppOptType = std::shared_ptr<::RNYIMCommon>;
    using JniType = jobject;

    using Boxed = NativeRNYIMCommon;

    ~NativeRNYIMCommon();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeRNYIMCommon>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeRNYIMCommon>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeRNYIMCommon();
    friend ::djinni::JniClass<NativeRNYIMCommon>;
    friend ::djinni::JniInterface<::RNYIMCommon, NativeRNYIMCommon>;

};

}  // namespace djinni_generated
