// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

#include "NativeRNYIMUserInfoManager.hpp"  // my header
#include "Marshal.hpp"
#include "NativeJavascriptCallback.hpp"
#include "NativeReactBridge.hpp"

namespace djinni_generated {

NativeRNYIMUserInfoManager::NativeRNYIMUserInfoManager() : ::djinni::JniInterface<::RNYIMUserInfoManager, NativeRNYIMUserInfoManager>("com/youme/imrn/jni/RNYIMUserInfoManager$CppProxy") {}

NativeRNYIMUserInfoManager::~NativeRNYIMUserInfoManager() = default;


CJNIEXPORT void JNICALL Java_com_youme_imrn_jni_RNYIMUserInfoManager_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::RNYIMUserInfoManager>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_youme_imrn_jni_RNYIMUserInfoManager_create(JNIEnv* jniEnv, jobject /*this*/, ::djinni_generated::NativeReactBridge::JniType j_bridge)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::RNYIMUserInfoManager::create(::djinni_generated::NativeReactBridge::toCpp(jniEnv, j_bridge));
        return ::djinni::release(::djinni_generated::NativeRNYIMUserInfoManager::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_youme_imrn_jni_RNYIMUserInfoManager_00024CppProxy_native_1SetUserInfo(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_nickName, jint j_sex, jstring j_personalSignature, jstring j_country, jstring j_province, jstring j_city, jstring j_extraInfo, ::djinni_generated::NativeJavascriptCallback::JniType j_callback)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::RNYIMUserInfoManager>(nativeRef);
        ref->SetUserInfo(::djinni::String::toCpp(jniEnv, j_nickName),
                         ::djinni::I32::toCpp(jniEnv, j_sex),
                         ::djinni::String::toCpp(jniEnv, j_personalSignature),
                         ::djinni::String::toCpp(jniEnv, j_country),
                         ::djinni::String::toCpp(jniEnv, j_province),
                         ::djinni::String::toCpp(jniEnv, j_city),
                         ::djinni::String::toCpp(jniEnv, j_extraInfo),
                         ::djinni_generated::NativeJavascriptCallback::toCpp(jniEnv, j_callback));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_youme_imrn_jni_RNYIMUserInfoManager_00024CppProxy_native_1SetUserHeadImage(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_path, ::djinni_generated::NativeJavascriptCallback::JniType j_callback)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::RNYIMUserInfoManager>(nativeRef);
        ref->SetUserHeadImage(::djinni::String::toCpp(jniEnv, j_path),
                              ::djinni_generated::NativeJavascriptCallback::toCpp(jniEnv, j_callback));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_youme_imrn_jni_RNYIMUserInfoManager_00024CppProxy_native_1QueryUserInfo(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_userID, ::djinni_generated::NativeJavascriptCallback::JniType j_callback)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::RNYIMUserInfoManager>(nativeRef);
        ref->QueryUserInfo(::djinni::String::toCpp(jniEnv, j_userID),
                           ::djinni_generated::NativeJavascriptCallback::toCpp(jniEnv, j_callback));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_youme_imrn_jni_RNYIMUserInfoManager_00024CppProxy_native_1SwitchUserStatus(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_userID, jint j_status, ::djinni_generated::NativeJavascriptCallback::JniType j_callback)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::RNYIMUserInfoManager>(nativeRef);
        ref->SwitchUserStatus(::djinni::String::toCpp(jniEnv, j_userID),
                              ::djinni::I32::toCpp(jniEnv, j_status),
                              ::djinni_generated::NativeJavascriptCallback::toCpp(jniEnv, j_callback));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_youme_imrn_jni_RNYIMUserInfoManager_00024CppProxy_native_1SetAddPermission(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jboolean j_beFound, jint j_beAddPermission, ::djinni_generated::NativeJavascriptCallback::JniType j_callback)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::RNYIMUserInfoManager>(nativeRef);
        ref->SetAddPermission(::djinni::Bool::toCpp(jniEnv, j_beFound),
                              ::djinni::I32::toCpp(jniEnv, j_beAddPermission),
                              ::djinni_generated::NativeJavascriptCallback::toCpp(jniEnv, j_callback));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

//CJNIEXPORT void JNICALL Java_com_youme_imrn_jni_RNYIMUserInfoManager_00024CppProxy_native_1SetUserExtendStatus(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_status, ::djinni_generated::NativeJavascriptCallback::JniType j_callback)
//{
//    try {
//        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
//        const auto& ref = ::djinni::objectFromHandleAddress<::RNYIMUserInfoManager>(nativeRef);
//        ref->SetUserExtendStatus(::djinni::String::toCpp(jniEnv, j_status),
//                                 ::djinni_generated::NativeJavascriptCallback::toCpp(jniEnv, j_callback));
//    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
//}

//CJNIEXPORT void JNICALL Java_com_youme_imrn_jni_RNYIMUserInfoManager_00024CppProxy_native_1SetHeaderImageUrl(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_url, ::djinni_generated::NativeJavascriptCallback::JniType j_callback)
//{
//    try {
//        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
//        const auto& ref = ::djinni::objectFromHandleAddress<::RNYIMUserInfoManager>(nativeRef);
//        ref->SetHeaderImageUrl(::djinni::String::toCpp(jniEnv, j_url),
//                               ::djinni_generated::NativeJavascriptCallback::toCpp(jniEnv, j_callback));
//    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
//}

}  // namespace djinni_generated
