// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

#pragma once

#include "RNYIMFriendManager.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeRNYIMFriendManager final : ::djinni::JniInterface<::RNYIMFriendManager, NativeRNYIMFriendManager> {
public:
    using CppType = std::shared_ptr<::RNYIMFriendManager>;
    using CppOptType = std::shared_ptr<::RNYIMFriendManager>;
    using JniType = jobject;

    using Boxed = NativeRNYIMFriendManager;

    ~NativeRNYIMFriendManager();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeRNYIMFriendManager>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeRNYIMFriendManager>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeRNYIMFriendManager();
    friend ::djinni::JniClass<NativeRNYIMFriendManager>;
    friend ::djinni::JniInterface<::RNYIMFriendManager, NativeRNYIMFriendManager>;

};

}  // namespace djinni_generated
