// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

#include "NativeRNYIMFriendManager.hpp"  // my header
#include "Marshal.hpp"
#include "NativeJavascriptCallback.hpp"
#include "NativeReactBridge.hpp"

namespace djinni_generated {

NativeRNYIMFriendManager::NativeRNYIMFriendManager() : ::djinni::JniInterface<::RNYIMFriendManager, NativeRNYIMFriendManager>("com/youme/imrn/jni/RNYIMFriendManager$CppProxy") {}

NativeRNYIMFriendManager::~NativeRNYIMFriendManager() = default;


CJNIEXPORT void JNICALL Java_com_youme_imrn_jni_RNYIMFriendManager_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::RNYIMFriendManager>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_youme_imrn_jni_RNYIMFriendManager_create(JNIEnv* jniEnv, jobject /*this*/, ::djinni_generated::NativeReactBridge::JniType j_bridge)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::RNYIMFriendManager::create(::djinni_generated::NativeReactBridge::toCpp(jniEnv, j_bridge));
        return ::djinni::release(::djinni_generated::NativeRNYIMFriendManager::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_youme_imrn_jni_RNYIMFriendManager_00024CppProxy_native_1RequestAddFriend(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_userID, jstring j_comments, ::djinni_generated::NativeJavascriptCallback::JniType j_callback)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::RNYIMFriendManager>(nativeRef);
        ref->RequestAddFriend(::djinni::String::toCpp(jniEnv, j_userID),
                              ::djinni::String::toCpp(jniEnv, j_comments),
                              ::djinni_generated::NativeJavascriptCallback::toCpp(jniEnv, j_callback));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_youme_imrn_jni_RNYIMFriendManager_00024CppProxy_native_1DealBeRequestAddFriend(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_userID, jint j_dealResult, ::djinni_generated::NativeJavascriptCallback::JniType j_callback)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::RNYIMFriendManager>(nativeRef);
        ref->DealBeRequestAddFriend(::djinni::String::toCpp(jniEnv, j_userID),
                                    ::djinni::I32::toCpp(jniEnv, j_dealResult),
                                    ::djinni_generated::NativeJavascriptCallback::toCpp(jniEnv, j_callback));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_youme_imrn_jni_RNYIMFriendManager_00024CppProxy_native_1DeleteFriend(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_userID, jint j_deleteType, ::djinni_generated::NativeJavascriptCallback::JniType j_callback)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::RNYIMFriendManager>(nativeRef);
        ref->DeleteFriend(::djinni::String::toCpp(jniEnv, j_userID),
                          ::djinni::I32::toCpp(jniEnv, j_deleteType),
                          ::djinni_generated::NativeJavascriptCallback::toCpp(jniEnv, j_callback));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_youme_imrn_jni_RNYIMFriendManager_00024CppProxy_native_1BlackFriend(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_type, jstring j_userID, ::djinni_generated::NativeJavascriptCallback::JniType j_callback)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::RNYIMFriendManager>(nativeRef);
        ref->BlackFriend(::djinni::I32::toCpp(jniEnv, j_type),
                         ::djinni::String::toCpp(jniEnv, j_userID),
                         ::djinni_generated::NativeJavascriptCallback::toCpp(jniEnv, j_callback));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_youme_imrn_jni_RNYIMFriendManager_00024CppProxy_native_1QueryFriends(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_type, jint j_startIndex, jint j_count, ::djinni_generated::NativeJavascriptCallback::JniType j_callback)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::RNYIMFriendManager>(nativeRef);
        ref->QueryFriends(::djinni::I32::toCpp(jniEnv, j_type),
                          ::djinni::I32::toCpp(jniEnv, j_startIndex),
                          ::djinni::I32::toCpp(jniEnv, j_count),
                          ::djinni_generated::NativeJavascriptCallback::toCpp(jniEnv, j_callback));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_youme_imrn_jni_RNYIMFriendManager_00024CppProxy_native_1QueryFriendRequestList(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_startIndex, jint j_count, ::djinni_generated::NativeJavascriptCallback::JniType j_callback)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::RNYIMFriendManager>(nativeRef);
        ref->QueryFriendRequestList(::djinni::I32::toCpp(jniEnv, j_startIndex),
                                    ::djinni::I32::toCpp(jniEnv, j_count),
                                    ::djinni_generated::NativeJavascriptCallback::toCpp(jniEnv, j_callback));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

//CJNIEXPORT void JNICALL Java_com_youme_imrn_jni_RNYIMFriendManager_00024CppProxy_native_1GetRecommandUser(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_startIndex, jint j_count, ::djinni_generated::NativeJavascriptCallback::JniType j_callback)
//{
//    try {
//        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
//        const auto& ref = ::djinni::objectFromHandleAddress<::RNYIMFriendManager>(nativeRef);
//        ref->GetRecommandUser(::djinni::I32::toCpp(jniEnv, j_startIndex),
//                              ::djinni::I32::toCpp(jniEnv, j_count),
//                              ::djinni_generated::NativeJavascriptCallback::toCpp(jniEnv, j_callback));
//    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
//}


}  // namespace djinni_generated
