// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

#include "NativeRNYIMLocationManager.hpp"  // my header
#include "Marshal.hpp"
#include "NativeJavascriptCallback.hpp"
#include "NativeReactBridge.hpp"

namespace djinni_generated {

NativeRNYIMLocationManager::NativeRNYIMLocationManager() : ::djinni::JniInterface<::RNYIMLocationManager, NativeRNYIMLocationManager>("com/youme/imrn/jni/RNYIMLocationManager$CppProxy") {}

NativeRNYIMLocationManager::~NativeRNYIMLocationManager() = default;


CJNIEXPORT void JNICALL Java_com_youme_imrn_jni_RNYIMLocationManager_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::RNYIMLocationManager>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_youme_imrn_jni_RNYIMLocationManager_create(JNIEnv* jniEnv, jobject /*this*/, ::djinni_generated::NativeReactBridge::JniType j_bridge)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::RNYIMLocationManager::create(::djinni_generated::NativeReactBridge::toCpp(jniEnv, j_bridge));
        return ::djinni::release(::djinni_generated::NativeRNYIMLocationManager::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_youme_imrn_jni_RNYIMLocationManager_00024CppProxy_native_1GetCurrentLocation(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, ::djinni_generated::NativeJavascriptCallback::JniType j_callback)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::RNYIMLocationManager>(nativeRef);
        ref->GetCurrentLocation(::djinni_generated::NativeJavascriptCallback::toCpp(jniEnv, j_callback));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_youme_imrn_jni_RNYIMLocationManager_00024CppProxy_native_1GetNearbyObjects(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_count, jstring j_serverAreaID, jint j_districtLevel, jboolean j_resetStartDistance, ::djinni_generated::NativeJavascriptCallback::JniType j_callback)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::RNYIMLocationManager>(nativeRef);
        ref->GetNearbyObjects(::djinni::I32::toCpp(jniEnv, j_count),
                              ::djinni::String::toCpp(jniEnv, j_serverAreaID),
                              ::djinni::I32::toCpp(jniEnv, j_districtLevel),
                              ::djinni::Bool::toCpp(jniEnv, j_resetStartDistance),
                              ::djinni_generated::NativeJavascriptCallback::toCpp(jniEnv, j_callback));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_youme_imrn_jni_RNYIMLocationManager_00024CppProxy_native_1GetDistance(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_userID, ::djinni_generated::NativeJavascriptCallback::JniType j_callback)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::RNYIMLocationManager>(nativeRef);
        ref->GetDistance(::djinni::String::toCpp(jniEnv, j_userID),
                         ::djinni_generated::NativeJavascriptCallback::toCpp(jniEnv, j_callback));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
