// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

#pragma once

#include "RNVoiceEngine.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeRNVoiceEngine final : ::djinni::JniInterface<::RNVoiceEngine, NativeRNVoiceEngine> {
public:
    using CppType = std::shared_ptr<::RNVoiceEngine>;
    using CppOptType = std::shared_ptr<::RNVoiceEngine>;
    using JniType = jobject;

    using Boxed = NativeRNVoiceEngine;

    ~NativeRNVoiceEngine();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeRNVoiceEngine>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeRNVoiceEngine>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeRNVoiceEngine();
    friend ::djinni::JniClass<NativeRNVoiceEngine>;
    friend ::djinni::JniInterface<::RNVoiceEngine, NativeRNVoiceEngine>;

};

}  // namespace djinni_generated
