// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

#pragma once

#include "RNYIMChannelManager.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeRNYIMChannelManager final : ::djinni::JniInterface<::RNYIMChannelManager, NativeRNYIMChannelManager> {
public:
    using CppType = std::shared_ptr<::RNYIMChannelManager>;
    using CppOptType = std::shared_ptr<::RNYIMChannelManager>;
    using JniType = jobject;

    using Boxed = NativeRNYIMChannelManager;

    ~NativeRNYIMChannelManager();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeRNYIMChannelManager>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeRNYIMChannelManager>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeRNYIMChannelManager();
    friend ::djinni::JniClass<NativeRNYIMChannelManager>;
    friend ::djinni::JniInterface<::RNYIMChannelManager, NativeRNYIMChannelManager>;

};

}  // namespace djinni_generated
