// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

#pragma once

#include "RNYIMManager.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeRNYIMManager final : ::djinni::JniInterface<::RNYIMManager, NativeRNYIMManager> {
public:
    using CppType = std::shared_ptr<::RNYIMManager>;
    using CppOptType = std::shared_ptr<::RNYIMManager>;
    using JniType = jobject;

    using Boxed = NativeRNYIMManager;

    ~NativeRNYIMManager();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeRNYIMManager>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeRNYIMManager>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeRNYIMManager();
    friend ::djinni::JniClass<NativeRNYIMManager>;
    friend ::djinni::JniInterface<::RNYIMManager, NativeRNYIMManager>;

};

}  // namespace djinni_generated
