// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

#include "RNYIMCommon.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class RCRNYIMCommon;

namespace djinni_generated {

class RNYIMCommon
{
public:
    using CppType = std::shared_ptr<::RNYIMCommon>;
    using CppOptType = std::shared_ptr<::RNYIMCommon>;
    using ObjcType = RCRNYIMCommon*;

    using Boxed = RNYIMCommon;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

