// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

#include "RNYIMManager.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class RCRNYIMManager;

namespace djinni_generated {

class RNYIMManager
{
public:
    using CppType = std::shared_ptr<::RNYIMManager>;
    using CppOptType = std::shared_ptr<::RNYIMManager>;
    using ObjcType = RCRNYIMManager*;

    using Boxed = RNYIMManager;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

