// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

#import "RVJavascriptCallback.h"
#import "RVReactBridge.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>
@class RCRNYIMManager;


/**----------------------------IM管理类---------------------------- */
@interface RCRNYIMManager : NSObject<RCTBridgeModule>

+ (nullable RCRNYIMManager *)create:(nullable id<RVReactBridge>)bridge;

/** 初始化 */
- (void)Init:(nullable NSString *)appkey
      secret:(nullable NSString *)secret
 packageName:(nullable NSString *)packageName
       model:(int)model
    callback:(nonnull RCTResponseSenderBlock)callback;

/**
 * 登录
 *Login(userID:string, password:string, promise:JavascriptPromise);	      				
 */
- (void)Login:(nullable NSString *)userID
     password:(nullable NSString *)password
     token:(nullable NSString *)token
     callback:(nonnull RCTResponseSenderBlock)callback;

/** 登出 */
- (void)Logout:(nonnull RCTResponseSenderBlock)callback;

/** 播放语音 */
- (void)StartPlayAudio:(nullable NSString *)path
              callback:(nonnull RCTResponseSenderBlock)callback;

/** 停止播放 */
- (void)StopPlayAudio:(nonnull RCTResponseSenderBlock)callback;

/** 获取最近联系人(最大100条) */
- (void)GetRecentContacts:(nonnull RCTResponseSenderBlock)callback;

/** 程序切到后台运行 */
- (void)OnPause;

/** 程序切到前台运行 */
- (void)OnResume;

/** 设置录音缓存目录 */
- (void)SetAudioRecordCacheDir:(nullable NSString *)path;

/** 获取语音缓存目录(返回值 path:string) */
- (void)GetAudioCachePath:(nonnull RCTResponseSenderBlock)callback;

/** 清理语音缓存目录(返回值 result:bool) */
- (void)ClearAudioCachePath;

/** 关键词过滤（返回值 text:string 过滤后文本, level:int 关键字等级） */
- (void)FilterKeyword:(nullable NSString *)text
             callback:(nonnull RCTResponseSenderBlock)callback;

@end
