// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

#import "RVJavascriptCallback.h"
#import "RVReactBridge.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>
@class RCRNYIMFriendManager;


/**----------------------------好友管理---------------------------- */
@interface RCRNYIMFriendManager : NSObject<RCTBridgeModule>

+ (nullable RCRNYIMFriendManager *)create:(nullable id<RVReactBridge>)bridge;

/** 功能：添加好友 */
- (void)RequestAddFriend:(nullable NSString *)userID
                comments:(nullable NSString *)comments
                callback:(nonnull RCTResponseSenderBlock)callback;

/** 处理被请求添加好友 (dealResult：处理结果	0：同意	1：拒绝) */
- (void)DealBeRequestAddFriend:(nullable NSString *)userID
                    dealResult:(int)dealResult
                      callback:(nonnull RCTResponseSenderBlock)callback;

/** 删除好友 deleteType：删除类型	0：双向删除	1：单向删除(删除方在被删除方好友列表依然存在) */
- (void)DeleteFriend:(nullable NSString *)userID
          deleteType:(int)deleteType
            callback:(nonnull RCTResponseSenderBlock)callback;

/** 拉黑好友 type：0：拉黑	1：解除拉黑 */
- (void)BlackFriend:(int)type
             userID:(nullable NSString *)userID
           callback:(nonnull RCTResponseSenderBlock)callback;

/** 查询我的好友 */
- (void)QueryFriends:(int)type
          startIndex:(int)startIndex
               count:(int)count
            callback:(nonnull RCTResponseSenderBlock)callback;

/** 查询好友请求列表 */
- (void)QueryFriendRequestList:(int)startIndex
                         count:(int)count
                      callback:(nonnull RCTResponseSenderBlock)callback;

/** 获取推荐好友 */
- (void)GetRecommandUser:(int)startIndex
                   count:(int)count
                callback:(nonnull RCTResponseSenderBlock)callback;

@end
