// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

#include "RNYIMUserInfoManager.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class RCRNYIMUserInfoManager;

namespace djinni_generated {

class RNYIMUserInfoManager
{
public:
    using CppType = std::shared_ptr<::RNYIMUserInfoManager>;
    using CppOptType = std::shared_ptr<::RNYIMUserInfoManager>;
    using ObjcType = RCRNYIMUserInfoManager*;

    using Boxed = RNYIMUserInfoManager;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

