// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

#import "RVJavascriptCallback.h"
#import "RVReactBridge.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>
@class RCRNYIMChannelManager;


/**----------------------------频道管理---------------------------- */
@interface RCRNYIMChannelManager : NSObject<RCTBridgeModule>

+ (nullable RCRNYIMChannelManager *)create:(nullable id<RVReactBridge>)bridge;

/** 进入IM频道 */
- (void)JoinChannel:(nullable NSString *)channelID
           callback:(nonnull RCTResponseSenderBlock)callback;

/** 离开IM频道 */
- (void)LeaveChannel:(nullable NSString *)channelID
            callback:(nonnull RCTResponseSenderBlock)callback;

@end
