// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

#import "RVJavascriptCallback.h"
#import "RVReactBridge.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>
@class RCRNYIMMessageManager;


/**----------------------------消息管理---------------------------- */
@interface RCRNYIMMessageManager : NSObject<RCTBridgeModule>

+ (nullable RCRNYIMMessageManager *)create:(nullable id<RVReactBridge>)bridge;

/** 发送文本消息（返回值 errorcode:int 错误码, requestID:string 请求ID） */
- (void)SendTextMessage:(nullable NSString *)receiverID
               chatType:(int)chatType
                   text:(nullable NSString *)text
               callback:(nonnull RCTResponseSenderBlock)callback;

/** 发送语音消息（返回值 errorcode:int 错误码, requestID:string 请求ID） */
- (void)SendAudioMessage:(nullable NSString *)receiverID
                chatType:(int)chatType
                callback:(nonnull RCTResponseSenderBlock)callback;

/** 发送语音消息（不带语音识别）（返回值 errorcode:int 错误码, requestID:string 请求ID） */
- (void)SendOnlyAudioMessage:(nullable NSString *)receiverID
                    chatType:(int)chatType
                    callback:(nonnull RCTResponseSenderBlock)callback;

/** 发送文件（返回值 errorcode:int 错误码, requestID:string 请求ID) */
- (void)SendFile:(nullable NSString *)receiverID
        chatType:(int)chatType
        filePath:(nullable NSString *)filePath
        fileType:(int)fileType
      extraParam:(nullable NSString *)extraParam
        callback:(nonnull RCTResponseSenderBlock)callback;

/** 停止语音消息 */
- (void)StopAudioMessage:(nullable NSString *)extraParam
                callback:(nonnull RCTResponseSenderBlock)callback;

/** 取消语音消息 */
- (void)CancelAudioMessage:(nonnull RCTResponseSenderBlock)callback;

/** 下载文件 */
- (void)DownloadFile:(nullable NSString *)messageID
            savePath:(nullable NSString *)savePath
            callback:(nonnull RCTResponseSenderBlock)callback;

/** 下载文件 */
- (void)DownloadFileByUrl:(nullable NSString *)url
                 savePath:(nullable NSString *)savePath
                 callback:(nonnull RCTResponseSenderBlock)callback;

- (void)SetMessageRead:(nullable NSString *) messageID
                isRead:(bool) isRead
              callback:(nonnull RCTResponseSenderBlock)callback;

- (void)SetAllMessageRead:(nullable NSString *) userID
                   isRead:(bool) isRead
                 callback:(nonnull RCTResponseSenderBlock)callback;

@end
