// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

#import "RVJavascriptCallback.h"
#import "RVReactBridge.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>
@class RCRNVoiceEngine;


/**----------------------------TALK---------------------------- */
@interface RCRNVoiceEngine : NSObject<RCTBridgeModule>

+ (nullable RCRNVoiceEngine *)create:(nullable id<RVReactBridge>)bridge;

/** 初始化 */
- (void)Init:(nullable NSString *)appkey
   appsecret:(nullable NSString *)appsecret
       model:(int)model
    callback:(nonnull RCTResponseSenderBlock)callback;

/** 加入语音频道 */
- (void)JoinChannelSingleMode:(nullable NSString *)userID
                      channel:(nullable NSString *)channel
                     userRole:(int)userRole
               checkRoomExist:(BOOL)checkRoomExist
                     callback:(nonnull RCTResponseSenderBlock)callback;

/** 退出所有语音频道 */
- (void)LeaveChannelAll:(nonnull RCTResponseSenderBlock)callback;

/** 设置扬声器静音 */
- (void)SetSpeakerMute:(BOOL)on
              callback:(nonnull RCTResponseSenderBlock)callback;

/** 设置麦克风静音 */
- (void)SetMicrophoneMute:(BOOL)mute
                 callback:(nonnull RCTResponseSenderBlock)callback;

/** 控制其他人的麦克风开关 */
- (void)SetOtherMicMute:(nullable NSString *)userID
                   mute:(BOOL)mute
               callback:(nonnull RCTResponseSenderBlock)callback;

/** 选择消除其他人的语音 */
- (void)SetListenOtherVoice:(nullable NSString *)userID
                         on:(BOOL)on
                   callback:(nonnull RCTResponseSenderBlock)callback;

/** 设置是否走扬声器输出 */
- (void)SetOutputToSpeaker:(BOOL)on
                 callback:(nonnull RCTResponseSenderBlock)callback;

/** 设置是否发送扬声器麦克风开关状态 */
- (void)SetAutoSendStatus:(BOOL)on
                  callback:(nonnull RCTResponseSenderBlock)callback;

- (void)RequestRestApi:(nullable NSString *)command
                  body: (nullable NSString *)body
              callback:(nonnull RCTResponseSenderBlock)callback;

@end
