// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

#include "RNYIMFriendManager.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class RCRNYIMFriendManager;

namespace djinni_generated {

class RNYIMFriendManager
{
public:
    using CppType = std::shared_ptr<::RNYIMFriendManager>;
    using CppOptType = std::shared_ptr<::RNYIMFriendManager>;
    using ObjcType = RCRNYIMFriendManager*;

    using Boxed = RNYIMFriendManager;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

