// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

#import "RVJavascriptCallback.h"
#import "RVReactBridge.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>
@class RCRNYIMUserInfoManager;


/**----------------------------用户管理---------------------------- */
@interface RCRNYIMUserInfoManager : NSObject<RCTBridgeModule>

+ (nullable RCRNYIMUserInfoManager *)create:(nullable id<RVReactBridge>)bridge;

/** 设置用户信息(extraInfo:自定义信息 json格式) */
- (void)SetUserInfo:(nullable NSString *)nickName
                sex:(int)sex
  personalSignature:(nullable NSString *)personalSignature
            country:(nullable NSString *)country
           province:(nullable NSString *)province
               city:(nullable NSString *)city
          extraInfo:(nullable NSString *)extraInfo
           callback:(nonnull RCTResponseSenderBlock)callback;

/** 设置用户头像 */
- (void)SetUserHeadImage:(nullable NSString *)path
                callback:(nonnull RCTResponseSenderBlock)callback;

/** 获取用户信息 */
- (void)QueryUserInfo:(nullable NSString *)userID
             callback:(nonnull RCTResponseSenderBlock)callback;

/** 切换用户状态 */
- (void)SwitchUserStatus:(nullable NSString *)userID
                  status:(int)status
                callback:(nonnull RCTResponseSenderBlock)callback;

/** 设置好友添加权限 */
- (void)SetAddPermission:(BOOL)beFound
         beAddPermission:(int)beAddPermission
                callback:(nonnull RCTResponseSenderBlock)callback;

/** 设置用户扩展状态 */
//- (void)SetUserExtendStatus:(nullable NSString *)status
//                   callback:(nonnull RCTResponseSenderBlock)callback;

/** 设置头像 */
//- (void)SetHeaderImageUrl:(nullable NSString *)url
//                 callback:(nonnull RCTResponseSenderBlock)callback;

@end
