// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

#include "RNYIMMessageManager.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class RCRNYIMMessageManager;

namespace djinni_generated {

class RNYIMMessageManager
{
public:
    using CppType = std::shared_ptr<::RNYIMMessageManager>;
    using CppOptType = std::shared_ptr<::RNYIMMessageManager>;
    using ObjcType = RCRNYIMMessageManager*;

    using Boxed = RNYIMMessageManager;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

