// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

#include "RNYIMLocationManager.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class RCRNYIMLocationManager;

namespace djinni_generated {

class RNYIMLocationManager
{
public:
    using CppType = std::shared_ptr<::RNYIMLocationManager>;
    using CppOptType = std::shared_ptr<::RNYIMLocationManager>;
    using ObjcType = RCRNYIMLocationManager*;

    using Boxed = RNYIMLocationManager;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

