// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

#import "RVReactBridge.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>
@class RCRNYIMCommon;

/**----------------------------listen module---------------------------- */
extern NSString * __nonnull const RCRNYIMCommonEVENTLOGIN;
/** 登录登出 */
extern NSString * __nonnull const RCRNYIMCommonEVENTCHANNEL;
/** 频道 */
extern NSString * __nonnull const RCRNYIMCommonEVENTUSERINFO;
/** 用户信息 */
extern NSString * __nonnull const RCRNYIMCommonEVENTFRIEND;
/** 好友 */
extern NSString * __nonnull const RCRNYIMCommonEVENTMESSAGE;
extern NSString * __nonnull const RCRNYIMCommonEVENTHISTORYMESSAGESERVER;
/** 消息管理 */
extern NSString * __nonnull const RCRNYIMCommonEVENTPLAY;
/** 语音播放 */
extern NSString * __nonnull const RCRNYIMCommonEVENTHISTORYMESSAGE;
/** 历史消息 */
extern NSString * __nonnull const RCRNYIMCommonEVENTLOCATION;
/** 地理位置 */
extern NSString * __nonnull const RCRNYIMCommonEVENTNOYYLOGIN;
/** noyy登录 */
extern NSString * __nonnull const RCRNYIMCommonEVENTNOYYCHANNEL;
/** noyy频道 */
extern NSString * __nonnull const RCRNYIMCommonEVENTVOICE;
/**
 * talk实时语音
 *----------------------------command----------------------------
 * 登录登出
 */
extern int32_t const RCRNYIMCommonCMDLOGIN;
/** 登录 */
extern int32_t const RCRNYIMCommonCMDLOGOUT;
/** 登出   */
extern int32_t const RCRNYIMCommonCMDKICKOFF;
/**
 * 被踢
 * 频道
 */
extern int32_t const RCRNYIMCommonCMDJOINROOM;
/** 进入房间 */
extern int32_t const RCRNYIMCommonCMDLEAVEROOM;
/**
 * 离开房间
 * 消息管理
 */
extern int32_t const RCRNYIMCommonCMDSENDMESSAGESTATUS;
/** 发送消息	 */
extern int32_t const RCRNYIMCommonCMDSTOPAUDIOMESSAGE;
/** 停止语音（发送端可在该回调触发时消息上屏）  */
extern int32_t const RCRNYIMCommonCMDSENDAUDIOMESSAGESTATUS;
/** 发送语音消息 */
extern int32_t const RCRNYIMCommonCMDCANCELAUDIOMESSAGE;
/** 取消语音 */
extern int32_t const RCRNYIMCommonCMDRECVMAEESAGNOTIFY;
/** 接收消息通知 */
extern int32_t const RCRNYIMCommonCMDDOWNLOADFILE;
/** 下载文件（根据消息ID下载） */
extern int32_t const RCRNYIMCommonCMDDOWNLOADFILEYBYURL;
/** 下载文件（更加URL下载） */
extern int32_t const RCRNYIMCommonCMDRECORDVOLUMECHANGE;
/** 录音音量变化 */
extern int32_t const RCRNYIMCommonCMDTEXTTANSLATE;
/** 文本翻译 */
extern int32_t const RCRNYIMCommonCMDRECENTCONTACTS;
/**
 * 获取最近联系人
 * 语音播放
 */
extern int32_t const RCRNYIMCommonCMDPLAYCOMPLETENOTIFY;
/** 播放完成 */
extern int32_t const RCRNYIMCommonCMDGETMICROPHONESTATUS;
/**
 * 获取麦克状态
 * 用户信息
 */
extern int32_t const RCRNYIMCommonCMDQUERYUSERINFO;
/** 查询用户信息 */
extern int32_t const RCRNYIMCommonCMDSETUSERINFO;
/** 设置用户信息 */
extern int32_t const RCRNYIMCommonCMDSWITCHUSERSTATUS;
/** 切换用户在线状态 */
extern int32_t const RCRNYIMCommonCMDSETHEADIMAGE;
/** 设置头像 */
extern int32_t const RCRNYIMCommonCMDUNSERINFOCHANGENOTIFY;
/** 用户信息变更通知 */
extern int32_t const RCRNYIMCommonCMDSETUSEREXTENDSTATUS;
/**
 * 设置用户扩展状态
 * 好友
 */
extern int32_t const RCRNYIMCommonCMDREQUESTADDFRIEND;
/** 请求添加好友 */
extern int32_t const RCRNYIMCommonCMDBEREQUESTADDFRIEND;
/** 被邀请添加好友通知（需要验证） */
extern int32_t const RCRNYIMCommonCMDBEADDFRIEND;
/** 被添加为好友通知（不需要验证） */
extern int32_t const RCRNYIMCommonCMDDEALBEREQUESTADDFRIEND;
/** 处理被请求添加好友 */
extern int32_t const RCRNYIMCommonCMDREQUESTADDFRIENDRESULTNOTIFY;
/** 请求添加好友结果通知 */
extern int32_t const RCRNYIMCommonCMDDELETEFRIEND;
/** 删除好友 */
extern int32_t const RCRNYIMCommonCMDBEDELETEFRIENDNOTIFY;
/** 被好友删除通知 */
extern int32_t const RCRNYIMCommonCMDBLACKFRIEND;
/** 拉黑或解除拉黑好友 */
extern int32_t const RCRNYIMCommonCMDQUERYFRIENDS;
/** 查询我的好友 */
extern int32_t const RCRNYIMCommonCMDQUERYFRIENDREQUESTLIST;
/** 查询好友请求列表 */
extern int32_t const RCRNYIMCommonCMDGETRECOMMANDUSER;
/**
 * 获取好友推荐  
 * 历史消息
 */
extern int32_t const RCRNYIMCommonCMDQUERYLOCALHISTORYMSG;
/** 查询本地历史消息 */
extern int32_t const RCRNYIMCommonCMDQUERYROOMHISTORYMSGSERVER;
/**
 * 查询服务端房间历史消息
 * 地理位置
 */
extern int32_t const RCRNYIMCommonCMDLOCATIONUPDATE;
/** 自己位置更新 */
extern int32_t const RCRNYIMCommonCMDLOCATIONGETNEARBYOBJECT;
/** 获取附近的人 */
extern int32_t const RCRNYIMCommonCMDLOCATIONGETDISTANCE;
/**
 * 获取与指定用户距离
 * noyy登录
 */
extern int32_t const RCRNYIMCommonCMDREGISTE;
/** 注册 */
extern int32_t const RCRNYIMCommonCMDHXRLOGIN;
/** 登录 */
extern int32_t const RCRNYIMCommonCMDRESETPASSWORD;
/** 重置密码 */
extern int32_t const RCRNYIMCommonCMDUPDATEPASSWORD;
/** 修改密码 */
extern int32_t const RCRNYIMCommonCMDMOBILEPHONEIDENTIFYINGCODE;
/**
 * 获取手机验证码
 * noyy频道
 */
extern int32_t const RCRNYIMCommonCMDCREATECHANNEL;
/** 创建频道 */
extern int32_t const RCRNYIMCommonCMDINVITEJOINCHANNEL;
/** 邀请用户加入频道 */
extern int32_t const RCRNYIMCommonCMDASKFORJOINCHANNEL;
/** 请求加入频道 */
extern int32_t const RCRNYIMCommonCMDLEAVECHANNEL;
/** 离开频道 */
extern int32_t const RCRNYIMCommonCMDMATCHCHANNEL;
/** 匹配频道 */
extern int32_t const RCRNYIMCommonCMDMATCHCHANNELRESULTNOTIFY;
/** 匹配频道结果通知 */
extern int32_t const RCRNYIMCommonCMDGETJOINEDCHANNEL;
/** 获取当前已加入频道 */
extern int32_t const RCRNYIMCommonCMDGETCHANNELMEMBER;
/** 获取频道成员 */
extern int32_t const RCRNYIMCommonCMDCHANNELMEMBERCHANGENOTIFY;
/** 频道成员变化通知 */
extern int32_t const RCRNYIMCommonCMDBEINVITEJOINCHANNEL;
/** 被邀请加入频道通知 */
extern int32_t const RCRNYIMCommonCMDSETCHANNELMATCHSWITCH;
/** 设置频道是否开启匹配 */
extern int32_t const RCRNYIMCommonCMDKICKCHANNELMEMBER;
/** 频道踢人 */
extern int32_t const RCRNYIMCommonCMDBEKICKNOTIFY;
/** 被踢出频道通知 */
extern int32_t const RCRNYIMCommonCMDDEVOLVECHANNELOWNER;
/** 转移频道主 */
extern int32_t const RCRNYIMCommonCMDBECOMCHANNELOWNERNOTIFY;
/** 成为频道主通知 */
extern int32_t const RCRNYIMCommonCMDFOLLOWJOINCHANNEL;
/** 跟随进入频道 */
extern int32_t const RCRNYIMCommonCMDFOLLOWJOINCHANNELREQUESTNOTIFY;
/** 请求跟随进入频道通知 */
extern int32_t const RCRNYIMCommonCMDVERIFYFOLLOWJOINCHANNEL;
/** 验证跟随进入频道 */
extern int32_t const RCRNYIMCommonCMDFOLLOWJOINCHANNELRESULTNOTIFY;
/**
 * 跟随进入频道结果通知
 * talk实时语音
 */
extern int32_t const RCRNYIMCommonCMDINIT;
/** 初始化 */
extern int32_t const RCRNYIMCommonCMDJOINCHANNEL;
/** 加入频道 */
extern int32_t const RCRNYIMCommonCMDLEAVEALLCHANNEL;
/** 离开所有语音频道 */
extern int32_t const RCRNYIMCommonCMDSELFSPEAKERCHANGE;
/** 扬声器状态变化 */
extern int32_t const RCRNYIMCommonCMDSELFMICROPHONECHANGE;
/** 麦克风状态变化 */
extern int32_t const RCRNYIMCommonCMDOTHERSPEAKERCHANGE;
extern int32_t const RCRNYIMCommonCMD_REST_API;
extern int32_t const RCRNYIMCommonCMD_MY_MIC_LEVEL;
/** 其他成员扬声器状态变化 */
extern int32_t const RCRNYIMCommonCMDOTHERMICROPHONECHANGE;
/** 其他成员麦克风状态变化 */
extern int32_t const RCRNYIMCommonCMDSPEAKERBECHANGE;
/** 扬声器状态被改变 */
extern int32_t const RCRNYIMCommonCMDMICROPHONEBECHANGE;
/** 麦克风状态被改变 */
extern int32_t const RCRNYIMCommonCMDOTHERSPEECHCHANGE;
/**
 * 其他用户讲话状态变化
 *----------------------------command end----------------------------
 * 环境
 */
extern int32_t const RCRNYIMCommonMODELFORMAL;
/** 线上环境 */
extern int32_t const RCRNYIMCommonMODELTEST;
/**
 * 测试环境
 * 消息来源类型
 */
extern int32_t const RCRNYIMCommonCHATTYPEPRIVATE;
/** 私聊 */
extern int32_t const RCRNYIMCommonCHATTYPECHANNEL;
/**
 * 频道消息
 * 消息类型
 */
extern int32_t const RCRNYIMCommonMESSAGETYPETEXT;
/** 文本消息 */
extern int32_t const RCRNYIMCommonMESSAGETYPECUSTOM;
/** 自定义消息 */
extern int32_t const RCRNYIMCommonMESSAGETYPEVOICE;
/** 语音消息 */
extern int32_t const RCRNYIMCommonMESSAGETYPEFILE;
/**
 * 文件消息
 * 文件类型
 */
extern int32_t const RCRNYIMCommonFILETYPEOTHER;
/** 其他 */
extern int32_t const RCRNYIMCommonFILETYPEAUDIO;
/** 音频 */
extern int32_t const RCRNYIMCommonFILETYPEIMAGE;
/** 图片 */
extern int32_t const RCRNYIMCommonFILETYPEVIDEO;
/**
 * 视频  
 * 语音识别语言
 */
extern int32_t const RCRNYIMCommonSPEECHLANGMANDARIN;
/** 普通话 */
extern int32_t const RCRNYIMCommonSPEECHLANGYUEYU;
/** 粤语 */
extern int32_t const RCRNYIMCommonSPEECHLANGSICHUAN;
/** 四川话 */
extern int32_t const RCRNYIMCommonSPEECHLANGHENAN;
/** 河南话 */
extern int32_t const RCRNYIMCommonSPEECHLANGENGLISH;
/** 英语 */
extern int32_t const RCRNYIMCommonSPEECHLANGTRADITIONAL;
/**
 * 繁体中文
 * 行政区划等级
 */
extern int32_t const RCRNYIMCommonDISTRICTLEVELUNKNOW;
extern int32_t const RCRNYIMCommonDISTRICTLEVELCOUNTRY;
/** 国家 */
extern int32_t const RCRNYIMCommonDISTRICTLEVELPROVINCE;
/** 省份 */
extern int32_t const RCRNYIMCommonDISTRICTLEVELCITY;
/** 市 */
extern int32_t const RCRNYIMCommonDISTRICTLEVELCOUNTY;
/** 区县 */
extern int32_t const RCRNYIMCommonDISTRICTLEVELSTREET;
/**
 * 街道
 * 性别
 */
extern int32_t const RCRNYIMCommonSEXUNKNOWN;
extern int32_t const RCRNYIMCommonSEXMALE;
extern int32_t const RCRNYIMCommonSEXFEMALE;
/** 用户在线状态 */
extern int32_t const RCRNYIMCommonSTATUSONLINE;
/** 在线 */
extern int32_t const RCRNYIMCommonSTATUSOFFLINE;
/** 离线 */
extern int32_t const RCRNYIMCommonSTATUSINVISIBLE;
/**
 * 隐身
 * 好友添加权限
 */
extern int32_t const RCRNYIMCommonNOTALLOWADD;
/** 不允许被添加 */
extern int32_t const RCRNYIMCommonNEEDVALIDATE;
/** 需要验证 */
extern int32_t const RCRNYIMCommonNOADDPERMISSION;
/**
 * 允许被添加，不需要验证, 默认值
 *----------------------------errorcode----------------------------
 */
extern int32_t const RCRNYIMCommonYIMERRORCODESUCCESS;
/** 成功 */
extern int32_t const RCRNYIMCommonYIMERRORCODEENGINENOTINIT;
/** 未初始化 */
extern int32_t const RCRNYIMCommonYIMERRORCODENOTLOGIN;
/** 未登录 */
extern int32_t const RCRNYIMCommonYIMERRORCODEPARAMINVALID;
/** 参数错误 */
extern int32_t const RCRNYIMCommonYIMERRORCODETIMEOUT;
/** 超时 */
extern int32_t const RCRNYIMCommonYIMERRORCODESTATUSERROR;
/** 状态错误 */
extern int32_t const RCRNYIMCommonYIMERRORCODESDKINVALID;
/** SDK验证识别 */
extern int32_t const RCRNYIMCommonYIMERRORCODEALREADYLOGIN;
/** 已经登录 */
extern int32_t const RCRNYIMCommonYIMERRORCODESERVERERROR;
/** 服务器错误 */
extern int32_t const RCRNYIMCommonYIMERRORCODENETERROR;
/** 网络错误 */
extern int32_t const RCRNYIMCommonYIMERRORCODELOGINSESSIONERROR;
/** session错误 */
extern int32_t const RCRNYIMCommonYIMERRORCODENOTSTARTUP;
/** 未启动 */
extern int32_t const RCRNYIMCommonYIMERRORCODEFILENOTEXIST;
/** 文件不存在 */
extern int32_t const RCRNYIMCommonYIMERRORCODESENDFILEERROR;
/** 发送文件失败 */
extern int32_t const RCRNYIMCommonYIMERRORCODEUPLOADFAILED;
/** 上传失败 */
extern int32_t const RCRNYIMCommonYIMERRORCODEUSERNAMEPASSWORDERROR;
/** 用户名密码错误	 */
extern int32_t const RCRNYIMCommonYIMERRORCODEUSERSTATUSERROR;
/** 用户状态错误(无效用户) */
extern int32_t const RCRNYIMCommonYIMERRORCODEMESSAGETOOLONG;
/** 消息太长 */
extern int32_t const RCRNYIMCommonYIMERRORCODERECEIVERTOOLONG;
/** 接收方ID过长(检查房间名) */
extern int32_t const RCRNYIMCommonYIMERRORCODEINVALIDCHATTYPE;
/** 无效聊天类型(私聊、聊天室) */
extern int32_t const RCRNYIMCommonYIMERRORCODEINVALIDRECEIVER;
/** 无效用户ID */
extern int32_t const RCRNYIMCommonYIMERRORCODEUNKNOWERROR;
extern int32_t const RCRNYIMCommonYIMERRORCODEINVALIDAPPKEY;
/** 无效APPKEY */
extern int32_t const RCRNYIMCommonYIMERRORCODEFORBIDDENSPEAK;
/** 被禁言 */
extern int32_t const RCRNYIMCommonYIMERRORCODECREATEFILEFAILED;
/** 创建文件失败 */
extern int32_t const RCRNYIMCommonYIMERRORCODEUNSUPPORTFORMAT;
/** 不支持的文件格式 */
extern int32_t const RCRNYIMCommonYIMERRORCODERECEIVEREMPTY;
/** 接收方为空 */
extern int32_t const RCRNYIMCommonYIMERRORCODEROOMIDTOOLONG;
/** 房间名太长 */
extern int32_t const RCRNYIMCommonYIMERRORCODECONTENTINVALID;
/** 聊天内容严重非法 */
extern int32_t const RCRNYIMCommonYIMERRORCODENOLOCATIONAUTHRIZE;
/** 未打开定位权限 */
extern int32_t const RCRNYIMCommonYIMERRORCODEUNKNOWLOCATION;
/** 未知位置 */
extern int32_t const RCRNYIMCommonYIMERRORCODEUNSUPPORT;
/** 不支持该接口 */
extern int32_t const RCRNYIMCommonYIMERRORCODENOAUDIODEVICE;
/** 无音频设备 */
extern int32_t const RCRNYIMCommonYIMERRORCODEAUDIODRIVER;
/** 音频驱动问题 */
extern int32_t const RCRNYIMCommonYIMERRORCODEDEVICESTATUSINVALID;
/** 设备状态错误 */
extern int32_t const RCRNYIMCommonYIMERRORCODERESOLVEFILEERROR;
/** 文件解析错误 */
extern int32_t const RCRNYIMCommonYIMERRORCODEREADWRITEFILEERROR;
/** 文件读写错误 */
extern int32_t const RCRNYIMCommonYIMERRORCODENOLANGCODE;
/** 语言编码错误 */
extern int32_t const RCRNYIMCommonYIMERRORCODETRANSLATEUNABLE;
/** 翻译接口不可用 */
extern int32_t const RCRNYIMCommonYIMERRORCODESPEECHACCENTINVALID;
/** 语音识别方言无效 */
extern int32_t const RCRNYIMCommonYIMERRORCODESPEECHLANGUAGEINVALID;
/** 语音识别语言无效 */
extern int32_t const RCRNYIMCommonYIMERRORCODEHASILLEGALTEXT;
/** 消息含非法字符 */
extern int32_t const RCRNYIMCommonYIMERRORCODEADVERTISEMENTMESSAGE;
/** 消息涉嫌广告 */
extern int32_t const RCRNYIMCommonYIMERRORCODEALREADYBLOCK;
/** 用户已经被屏蔽 */
extern int32_t const RCRNYIMCommonYIMERRORCODENOTBLOCK;
/** 用户未被屏蔽 */
extern int32_t const RCRNYIMCommonYIMERRORCODEMESSAGEBLOCKED;
/** 消息被屏蔽 */
extern int32_t const RCRNYIMCommonYIMERRORCODELOCATIONTIMEOUT;
/** 定位超时 */
extern int32_t const RCRNYIMCommonYIMERRORCODENOTJOINROOM;
/** 未加入该房间 */
extern int32_t const RCRNYIMCommonYIMERRORCODELOGINTOKENINVALID;
/** 登录token错误 */
extern int32_t const RCRNYIMCommonYIMERRORCODECREATEDIRECTORYFAILED;
/** 创建目录失败 */
extern int32_t const RCRNYIMCommonYIMERRORCODEINITFAILED;
/** 初始化失败 */
extern int32_t const RCRNYIMCommonYIMERRORCODEDISCONNECT;
/** 与服务器断开 */
extern int32_t const RCRNYIMCommonYIMERRORCODETHESAMEPARAM;
/** 设置参数相同 */
extern int32_t const RCRNYIMCommonYIMERRORCODEQUERYUSERINFOFAIL;
/** 查询用户信息失败 */
extern int32_t const RCRNYIMCommonYIMERRORCODESETUSERINFOFAIL;
/** 设置用户信息失败 */
extern int32_t const RCRNYIMCommonYIMERRORCODEUPDATEUSERONLINESTATEFAIL;
/** 更新用户在线状态失败 */
extern int32_t const RCRNYIMCommonYIMERRORCODENICKNAMETOOLONG;
/** 昵称太长(> 64 bytes) */
extern int32_t const RCRNYIMCommonYIMERRORCODESIGNATURETOOLONG;
/** 个性签名太长(> 120 bytes) */
extern int32_t const RCRNYIMCommonYIMERRORCODENEEDFRIENDVERIFY;
/** 需要好友验证信息 */
extern int32_t const RCRNYIMCommonYIMERRORCODEBEREFUSE;
/** 添加好友被拒绝 */
extern int32_t const RCRNYIMCommonYIMERRORCODEHASNOTREGISTERUSERINFO;
/** 未注册用户信息 */
extern int32_t const RCRNYIMCommonYIMERRORCODEALREADYFRIEND;
/** 已经是好友 */
extern int32_t const RCRNYIMCommonYIMERRORCODENOTFRIEND;
/** 非好友 */
extern int32_t const RCRNYIMCommonYIMERRORCODENOTBLACK;
/** 不在黑名单中 */
extern int32_t const RCRNYIMCommonYIMERRORCODEPHOTOURLTOOLONG;
/** 头像url过长(>500 bytes) */
extern int32_t const RCRNYIMCommonYIMERRORCODEPHOTOSIZETOOLARGE;
/**
 * 头像太大（>100 kb）
 * 服务错误码
 */
extern int32_t const RCRNYIMCommonYIMERRORCODEALREADYFRIENDS;
extern int32_t const RCRNYIMCommonYIMERRORCODELOGININVALID;
/** 语音部分错误码 */
extern int32_t const RCRNYIMCommonYIMERRORCODEPTTSTART;
extern int32_t const RCRNYIMCommonYIMERRORCODEPTTFAIL;
extern int32_t const RCRNYIMCommonYIMERRORCODEPTTDOWNLOADFAIL;
/** 下载语音失败 */
extern int32_t const RCRNYIMCommonYIMERRORCODEPTTGETUPLOADTOKENFAIL;
/** 获取token失败 */
extern int32_t const RCRNYIMCommonYIMERRORCODEPTTUPLOADFAIL;
/** 上传失败 */
extern int32_t const RCRNYIMCommonYIMERRORCODEPTTNOTSPEECH;
/** 未检测到语音或未开始语音 */
extern int32_t const RCRNYIMCommonYIMERRORCODEPTTDEVICESTATUSERROR;
/** 音频设备状态错误 */
extern int32_t const RCRNYIMCommonYIMERRORCODEPTTISSPEECHING;
/** 正在录音 */
extern int32_t const RCRNYIMCommonYIMERRORCODEPTTFILENOTEXIST;
/** 文件不存在 */
extern int32_t const RCRNYIMCommonYIMERRORCODEPTTREACHMAXDURATION;
/** 达到语音最大时长限制 */
extern int32_t const RCRNYIMCommonYIMERRORCODEPTTSPEECHTOOSHORT;
/** 语音时长太短 */
extern int32_t const RCRNYIMCommonYIMERRORCODEPTTSTARTAUDIORECORDFAILED;
/** 启动录音失败 */
extern int32_t const RCRNYIMCommonYIMERRORCODEPTTSPEECHTIMEOUT;
/** 音频输入超时 */
extern int32_t const RCRNYIMCommonYIMERRORCODEPTTISPLAYING;
/** 正在播放 */
extern int32_t const RCRNYIMCommonYIMERRORCODEPTTNOTSTARTPLAY;
/** 未开始播放 */
extern int32_t const RCRNYIMCommonYIMERRORCODEPTTCANCELPLAY;
/** 主动取消播放 */
extern int32_t const RCRNYIMCommonYIMERRORCODEPTTNOTSTARTRECORD;
/** 未开始语音 */
extern int32_t const RCRNYIMCommonYIMERRORCODEPTTNOTINIT;
/**  未初始化 */
extern int32_t const RCRNYIMCommonYIMERRORCODEPTTINITFAILED;
/**  初始化失败 */
extern int32_t const RCRNYIMCommonYIMERRORCODEPTTAUTHORIZE;
/**  录音权限 */
extern int32_t const RCRNYIMCommonYIMERRORCODEPTTSTARTRECORDFAILED;
/**  启动录音失败 */
extern int32_t const RCRNYIMCommonYIMERRORCODEPTTSTOPRECORDFAILED;
/**  停止录音失败 */
extern int32_t const RCRNYIMCommonYIMERRORCODEPTTUNSUPPRTFORMAT;
/**  不支持的格式 */
extern int32_t const RCRNYIMCommonYIMERRORCODEPTTRESOLVEFILEERROR;
/**  解析文件错误 */
extern int32_t const RCRNYIMCommonYIMERRORCODEPTTREADWRITEFILEERROR;
/**  读写文件错误 */
extern int32_t const RCRNYIMCommonYIMERRORCODEPTTCONVERTFILEFAILED;
/**  文件转换失败 */
extern int32_t const RCRNYIMCommonYIMERRORCODEPTTNOAUDIODEVICE;
/**  无音频设备 */
extern int32_t const RCRNYIMCommonYIMERRORCODEPTTNODRIVER;
/**  驱动问题 */
extern int32_t const RCRNYIMCommonYIMERRORCODEPTTSTARTPLAYFAILED;
/**  启动播放失败 */
extern int32_t const RCRNYIMCommonYIMERRORCODEPTTSTOPPLAYFAILED;
/**
 *  停止播放失败
 * -------------------------- NOYY --------------------------
 */
extern int32_t const RCRNYIMCommonYIMERRORCODEIDENTITYCODEERROR;
/**  验证码错误 */
extern int32_t const RCRNYIMCommonYIMERRORCODEUSEREXIST;
/**  用户已存在 */
extern int32_t const RCRNYIMCommonYIMERRORCODEUSERNOTEXIST;
/**  用户不存在 */
extern int32_t const RCRNYIMCommonYIMERRORCODEPASSWORDERROR;
/**  密码错误 */
extern int32_t const RCRNYIMCommonYIMERRORCODENEWOLDPASSSAME;
/**  新旧密码相同 */
extern int32_t const RCRNYIMCommonYIMERRORCODENOTJOINCHANNEL;
/**  未加入频道 */
extern int32_t const RCRNYIMCommonYIMERRORCODEALREADYJOINCHANNEL;
/**  已加入频道 */
extern int32_t const RCRNYIMCommonYIMERRORCODECHANNELMEMBERFULL;
/**  频道成员已满 */
extern int32_t const RCRNYIMCommonYIMERRORCODEMATCHTIMEOUT;
/**  匹配超时 */
extern int32_t const RCRNYIMCommonYIMERRORCODECHANNELDISABLED;
/**  频道不可用 */
extern int32_t const RCRNYIMCommonYIMERRORCODENOTCHANNELOWNER;
/**
 *  频道不可用
 * -------------------------- NOYY --------------------------
 */
extern int32_t const RCRNYIMCommonYIMERRORCODEFAIL;
/** -------------------------- TALK -------------------------- */
extern int32_t const RCRNYIMCommonYOUMEUSERNONE;
/** 非法用户 */
extern int32_t const RCRNYIMCommonYOUMEUSERTALKERFREE;
/** 自由讲话者 */
extern int32_t const RCRNYIMCommonYOUMEUSERTALKERONDEMAND;
/** 抢麦 */
extern int32_t const RCRNYIMCommonYOUMEUSERLISTENER;
/** 听众 */
extern int32_t const RCRNYIMCommonYOUMEUSERCOMMANDER;
/** 指挥 */
extern int32_t const RCRNYIMCommonYOUMEUSERHOST;
/** 主播 */
extern int32_t const RCRNYIMCommonYOUMEUSERGUSET;
/**
 * 嘉宾
 * ---------------- errorcode ----------------
 */
extern int32_t const RCRNYIMCommonYOUMESUCCESS;
/**
 *成功
 * 参数和状态检查
 */
extern int32_t const RCRNYIMCommonYOUMEERRORAPINOTSUPPORTED;
/**正在使用的SDK不支持特定的API */
extern int32_t const RCRNYIMCommonYOUMEERRORINVALIDPARAM;
/**传入参数错误 */
extern int32_t const RCRNYIMCommonYOUMEERRORALREADYINIT;
/**已经初始化 */
extern int32_t const RCRNYIMCommonYOUMEERRORNOTINIT;
/**还没有初始化，在调用某函数之前要先调用初始化并且要根据返回值确保初始化成功 */
extern int32_t const RCRNYIMCommonYOUMEERRORCHANNELEXIST;
/**要加入的频道已经存在 */
extern int32_t const RCRNYIMCommonYOUMEERRORCHANNELNOTEXIST;
/**对频道进入（检查参数为true时）、退出、讲话、设置白名单、抢麦等接口时频道不存在 */
extern int32_t const RCRNYIMCommonYOUMEERRORWRONGSTATE;
/**状态错误 */
extern int32_t const RCRNYIMCommonYOUMEERRORNOTALLOWEDMOBILENETWROK;
/**不允许使用移动网络 */
extern int32_t const RCRNYIMCommonYOUMEERRORWRONGCHANNELMODE;
/**在单频道模式下调用了多频道接口，或者反之 */
extern int32_t const RCRNYIMCommonYOUMEERRORTOOMANYCHANNELS;
/**同时加入了太多频道 */
extern int32_t const RCRNYIMCommonYOUMEERRORTOKENERROR;
/**传入的token认证错误 */
extern int32_t const RCRNYIMCommonYOUMEERRORNOTINCHANNEL;
/**用户不在该频道 */
extern int32_t const RCRNYIMCommonYOUMEERRORBEKICK;
/**
 *被踢了，还在禁止时间内，不允许进入房间
 * 内部操作错误
 */
extern int32_t const RCRNYIMCommonYOUMEERRORMEMORYOUT;
/**内存错误 */
extern int32_t const RCRNYIMCommonYOUMEERRORSTARTFAILED;
/**启动引擎失败 */
extern int32_t const RCRNYIMCommonYOUMEERRORSTOPFAILED;
/** 停止引擎失败 */
extern int32_t const RCRNYIMCommonYOUMEERRORILLEGALSDK;
/**非法使用SDK */
extern int32_t const RCRNYIMCommonYOUMEERRORSERVERINVALID;
/**语音服务不可用 */
extern int32_t const RCRNYIMCommonYOUMEERRORNETWORKERROR;
/**网络错误 */
extern int32_t const RCRNYIMCommonYOUMEERRORSERVERINTERERROR;
/**服务器内部错误 */
extern int32_t const RCRNYIMCommonYOUMEERRORQUERYRESTAPIFAIL;
/**请求RestApi信息失败了 */
extern int32_t const RCRNYIMCommonYOUMEERRORUSERABORT;
/**用户请求中断当前操作 */
extern int32_t const RCRNYIMCommonYOUMEERRORSENDMESSAGEFAIL;
/**
 *发送消息失败
 * 麦克风错误
 */
extern int32_t const RCRNYIMCommonYOUMEERRORRECINITFAILED;
/**录音模块初始化失败 */
extern int32_t const RCRNYIMCommonYOUMEERRORRECNOPERMISSION;
/**没有录音权限 */
extern int32_t const RCRNYIMCommonYOUMEERRORRECNODATA;
/**虽然初始化成功，但没有音频数据输出，比如oppo系列手机在录音权限被禁止的时候 */
extern int32_t const RCRNYIMCommonYOUMEERRORRECOTHERS;
/**其他录音模块的错误 */
extern int32_t const RCRNYIMCommonYOUMEERRORRECPERMISSIONUNDEFINED;
/**
 *录音权限未确定，iOS显示是否允许录音权限对话框时，返回的是这个错误码
 * 抢麦错误
 */
extern int32_t const RCRNYIMCommonYOUMEERRORGRABMICFULL;
/**抢麦失败，人数满 */
extern int32_t const RCRNYIMCommonYOUMEERRORGRABMICHASEND;
/**
 *抢麦失败，活动已经结束
 * 连麦错误
 */
extern int32_t const RCRNYIMCommonYOUMEERRORINVITEMICNOUSER;
/**连麦失败，用户不存在 */
extern int32_t const RCRNYIMCommonYOUMEERRORINVITEMICOFFLINE;
/**连麦失败，用户已离线 */
extern int32_t const RCRNYIMCommonYOUMEERRORINVITEMICREJECT;
/**连麦失败，用户拒绝 */
extern int32_t const RCRNYIMCommonYOUMEERRORINVITEMICTIMEOUT;
/**
 *连麦失败，两种情况：1.连麦时，对方超时无应答 2.通话中，双方通话时间到
 * 频道白名单错误
 */
extern int32_t const RCRNYIMCommonYOUMEERRORWHITESOMEUSERABNORMAL;
/**设置白名单部分用户异常：已不在房间 */
extern int32_t const RCRNYIMCommonYOUMEERRORUNKNOWN;

@interface RCRNYIMCommon : NSObject<RCTBridgeModule>

+ (nullable RCRNYIMCommon *)create:(nullable id<RVReactBridge>)bridge;

@end
