// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

#import "RVJavascriptCallback.h"
#import "RVReactBridge.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>
@class RCRNYIMHistoryMessageManager;


/**----------------------------历史消息管理---------------------------- */
@interface RCRNYIMHistoryMessageManager : NSObject<RCTBridgeModule>

+ (nullable RCRNYIMHistoryMessageManager *)create:(nullable id<RVReactBridge>)bridge;

/** 查询本地历史消息 */
- (void)QueryHistoryMessage:(nullable NSString *)targetID
                   chatType:(int)chatType
             startMessageID:(nullable NSString *)startMessageID
                      count:(int)count
                  direction:(int)direction
                   callback:(nonnull RCTResponseSenderBlock)callback;

/** 查询服务端房间最近历史消息 */
- (void)QueryRoomHistoryMessageFromServer:(nullable NSString *)roomID
                                    count:(int)count
                                direction:(int)direction
                                 callback:(nonnull RCTResponseSenderBlock)callback;

/** 删除本地历史消息 */
- (void)DeleteHistoryMessage:(nullable NSString *)targetID
                    chatType:(int)chatType
              startMessageID:(nullable NSString *)startMessageID
                       count:(int)count
                    callback:(nonnull RCTResponseSenderBlock)callback;

/** 删除本地历史消息 */
- (void)DeleteHistoryMessageByID:(nullable NSString *)messageID
                        callback:(nonnull RCTResponseSenderBlock)callback;

- (void)SetRoomHistoryMessageSwitch:(nullable NSString *)targetID
                           save:(BOOL)save
                           callback:(nonnull RCTResponseSenderBlock)callback;

@end
