// AUTOGENERATED!
#pragma once

#import "RCDjinniModulesInitializer.h"
#import "RCRNVoiceEngine.h"
#import "RCRNYIMChannelManager.h"
#import "RCRNYIMCommon.h"
#import "RCRNYIMFriendManager.h"
#import "RCRNYIMHistoryMessageManager.h"
#import "RCRNYIMLocationManager.h"
#import "RCRNYIMManager.h"
#import "RCRNYIMMessageManager.h"
#import "RCRNYIMUserInfoManager.h"
