// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

package com.youme.imrn.jni;

import com.facebook.react.bridge.Callback;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.ReadableArray;
import com.facebook.react.bridge.ReadableMap;
import com.facebook.react.bridge.WritableArray;
import com.facebook.react.bridge.WritableMap;
import com.facebook.react.module.annotations.ReactModule;
import com.youme.reactcpp.ReactDjinni;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.atomic.AtomicBoolean;

@ReactModule(name = "RNYIMCommon")
public final class RNYIMCommon extends ReactContextBaseJavaModule {
    /**----------------------------listen module---------------------------- */
    public static final String EVENT_LOGIN = "EVENT_LOGIN";

    /** 登录登出 */
    public static final String EVENT_CHANNEL = "EVENT_CHANNEL";

    /** 频道 */
    public static final String EVENT_USERINFO = "EVENT_USERINFO";

    /** 用户信息 */
    public static final String EVENT_FRIEND = "EVENT_FRIEND";

    /** 好友 */
    public static final String EVENT_MESSAGE = "EVENT_MESSAGE";

    /** 消息管理 */
    public static final String EVENT_PLAY = "EVENT_PLAY";

    /** 语音播放 */
    public static final String EVENT_HISTORYMESSAGE = "EVENT_HISTORYMESSAGE";

    public static final String EVENT_HISTORYMESSAGE_SERVER = "EVENT_HISTORYMESSAGE_SERVER";

    /** 历史消息 */
    public static final String EVENT_LOCATION = "EVENT_LOCATION";

    /** 地理位置 */
    public static final String EVENT_NOYYLOGIN = "EVENT_NOYYLOGIN";

    /** noyy登录 */
    public static final String EVENT_NOYYCHANNEL = "EVENT_LOCATION";

    /** noyy频道 */
    public static final String EVENT_VOICE = "EVENT_VOICE";

    /**
     * talk实时语音
     *----------------------------command----------------------------
     * 登录登出
     */
    public static final int CMD_LOGIN = 100;

    /** 登录 */
    public static final int CMD_LOGOUT = 101;

    /** 登出   */
    public static final int CMD_KICKOFF = 102;

    /**
     * 被踢
     * 频道
     */
    public static final int CMD_JOIN_ROOM = 200;

    /** 进入房间 */
    public static final int CMD_LEAVE_ROOM = 201;

    /**
     * 离开房间
     * 消息管理
     */
    public static final int CMD_SEND_MESSAGE_STATUS = 300;

    /** 发送消息	 */
    public static final int CMD_STOP_AUDIO_MESSAGE = 302;

    /** 停止语音（发送端可在该回调触发时消息上屏）  */
    public static final int CMD_SEND_AUDIO_MESSAGE_STATUS = 303;

    /** 发送语音消息 */
    public static final int CMD_CANCEL_AUDIO_MESSAGE = 304;

    /** 取消语音 */
    public static final int CMD_RECV_MAEESAG_NOTIFY = 305;

    /** 接收消息通知 */
    public static final int CMD_DOWNLOAD_FILE = 306;

    /** 下载文件（根据消息ID下载） */
    public static final int CMD_DOWNLOAD_FILEY_BY_URL = 307;

    /** 下载文件（更加URL下载） */
    public static final int CMD_RECORD_VOLUME_CHANGE = 308;

    /** 录音音量变化 */
    public static final int CMD_TEXT_TANSLATE = 309;

    /** 文本翻译 */
    public static final int CMD_RECENT_CONTACTS = 310;

    /**
     * 获取最近联系人
     * 语音播放
     */
    public static final int CMD_PLAY_COMPLETE_NOTIFY = 400;

    /** 播放完成 */
    public static final int CMD_GET_MICROPHONE_STATUS = 401;

    /**
     * 获取麦克状态
     * 用户信息
     */
    public static final int CMD_QUERY_USER_INFO = 500;

    /** 查询用户信息 */
    public static final int CMD_SET_USER_INFO = 501;

    /** 设置用户信息 */
    public static final int CMD_SWITCH_USER_STATUS = 502;

    /** 切换用户在线状态 */
    public static final int CMD_SET_HEAD_IMAGE = 503;

    /** 设置头像 */
    public static final int CMD_UNSER_INFO_CHANGE_NOTIFY = 504;

    /** 用户信息变更通知 */
    public static final int CMD_SET_USER_EXTEND_STATUS = 505;

    /**
     * 设置用户扩展状态
     * 好友
     */
    public static final int CMD_REQUEST_ADD_FRIEND = 600;

    /** 请求添加好友 */
    public static final int CMD_BE_REQUEST_ADD_FRIEND = 601;

    /** 被邀请添加好友通知（需要验证） */
    public static final int CMD_BE_ADD_FRIEND = 602;

    /** 被添加为好友通知（不需要验证） */
    public static final int CMD_DEAL_BE_REQUEST_ADD_FRIEND = 603;

    /** 处理被请求添加好友 */
    public static final int CMD_REQUEST_ADD_FRIEND_RESULT_NOTIFY = 604;

    /** 请求添加好友结果通知 */
    public static final int CMD_DELETE_FRIEND = 605;

    /** 删除好友 */
    public static final int CMD_BE_DELETE_FRIEND_NOTIFY = 606;

    /** 被好友删除通知 */
    public static final int CMD_BLACK_FRIEND = 607;

    /** 拉黑或解除拉黑好友 */
    public static final int CMD_QUERY_FRIENDS = 608;

    /** 查询我的好友 */
    public static final int CMD_QUERY_FRIEND_REQUEST_LIST = 609;

    /** 查询好友请求列表 */
    public static final int CMD_GET_RECOMMAND_USER = 610;

    /**
     * 获取好友推荐  
     * 历史消息
     */
    public static final int CMD_QUERY_LOCAL_HISTORY_MSG = 701;

    /** 查询本地历史消息 */
    public static final int CMD_QUERY_ROOM_HISTORY_MSG_SERVER = 702;

    /**
     * 查询服务端房间历史消息
     * 地理位置
     */
    public static final int CMD_LOCATION_UPDATE = 800;

    /** 自己位置更新 */
    public static final int CMD_LOCATION_GET_NEARBY_OBJECT = 801;

    /** 获取附近的人 */
    public static final int CMD_LOCATION_GET_DISTANCE = 802;

    /**
     * 获取与指定用户距离
     * noyy登录
     */
    public static final int CMD_REGISTE = 900;

    /** 注册 */
    public static final int CMD_HXRLOGIN = 901;

    /** 登录 */
    public static final int CMD_RESET_PASSWORD = 902;

    /** 重置密码 */
    public static final int CMD_UPDATE_PASSWORD = 903;

    /** 修改密码 */
    public static final int CMD_MOBILEPHONE_IDENTIFYING_CODE = 904;

    /**
     * 获取手机验证码
     * noyy频道
     */
    public static final int CMD_CREATE_CHANNEL = 1000;

    /** 创建频道 */
    public static final int CMD_INVITE_JOIN_CHANNEL = 1002;

    /** 邀请用户加入频道 */
    public static final int CMD_ASKFOR_JOIN_CHANNEL = 1003;

    /** 请求加入频道 */
    public static final int CMD_LEAVE_CHANNEL = 1004;

    /** 离开频道 */
    public static final int CMD_MATCH_CHANNEL = 1005;

    /** 匹配频道 */
    public static final int CMD_MATCH_CHANNEL_RESULT_NOTIFY = 10006;

    /** 匹配频道结果通知 */
    public static final int CMD_GET_JOINED_CHANNEL = 1007;

    /** 获取当前已加入频道 */
    public static final int CMD_GET_CHANNEL_MEMBER = 1008;

    /** 获取频道成员 */
    public static final int CMD_CHANNEL_MEMBER_CHANGE_NOTIFY = 1009;

    /** 频道成员变化通知 */
    public static final int CMD_BE_INVITE_JOIN_CHANNEL = 1010;

    /** 被邀请加入频道通知 */
    public static final int CMD_SET_CHANNEL_MATCH_SWITCH = 1011;

    /** 设置频道是否开启匹配 */
    public static final int CMD_KICK_CHANNEL_MEMBER = 1012;

    /** 频道踢人 */
    public static final int CMD_BE_KICK_NOTIFY = 1013;

    /** 被踢出频道通知 */
    public static final int CMD_DEVOLVE_CHANNEL_OWNER = 1014;

    /** 转移频道主 */
    public static final int CMD_BECOM_CHANNEL_OWNER_NOTIFY = 1015;

    /** 成为频道主通知 */
    public static final int CMD_FOLLOW_JOIN_CHANNEL = 1016;

    /** 跟随进入频道 */
    public static final int CMD_FOLLOW_JOIN_CHANNEL_REQUEST_NOTIFY = 1017;

    /** 请求跟随进入频道通知 */
    public static final int CMD_VERIFY_FOLLOW_JOIN_CHANNEL = 1018;

    /** 验证跟随进入频道 */
    public static final int CMD_FOLLOW_JOIN_CHANNEL_RESULT_NOTIFY = 1019;

    /**
     * 跟随进入频道结果通知
     * talk实时语音
     */
    public static final int CMD_INIT = 1100;

    /** 初始化 */
    public static final int CMD_JOIN_CHANNEL = 1101;

    /** 加入频道 */
    public static final int CMD_LEAVE_ALL_CHANNEL = 1102;

    /** 离开所有语音频道 */
    public static final int CMD_SELF_SPEAKER_CHANGE = 1103;

    /** 扬声器状态变化 */
    public static final int CMD_SELF_MICROPHONE_CHANGE = 1104;

    /** 麦克风状态变化 */
    public static final int CMD_OTHER_SPEAKER_CHANGE = 1105;

    /** 其他成员扬声器状态变化 */
    public static final int CMD_OTHER_MICROPHONE_CHANGE = 1106;

    /** 其他成员麦克风状态变化 */
    public static final int CMD_SPEAKER_BE_CHANGE = 1107;

    /** 扬声器状态被改变 */
    public static final int CMD_MICROPHONE_BE_CHANGE = 1108;

    /** VAD状态被改变 */
    public static final int CMD_OTHER_SPEECH_CHANGE = 1109;

    public static final int CMD_REST_API = 1110;

    public static final int CMD_MY_MIC_LEVEL = 1111;

    /**
     * 其他用户讲话状态变化
     *----------------------------command end----------------------------
     * 环境
     */
    public static final int MODEL_FORMAL = 0;

    /** 线上环境 */
    public static final int MODEL_TEST = 1;

    /**
     * 测试环境
     * 消息来源类型
     */
    public static final int CHATTYPE_PRIVATE = 1;

    /** 私聊 */
    public static final int CHATTYPE_CHANNEL = 2;

    /**
     * 频道消息
     * 消息类型
     */
    public static final int MESSAGETYPE_TEXT = 1;

    /** 文本消息 */
    public static final int MESSAGETYPE_CUSTOM = 2;

    /** 自定义消息 */
    public static final int MESSAGETYPE_VOICE = 5;

    /** 语音消息 */
    public static final int MESSAGETYPE_FILE = 7;

    /**
     * 文件消息
     * 文件类型
     */
    public static final int FILETYPE_OTHER = 0;

    /** 其他 */
    public static final int FILETYPE_AUDIO = 1;

    /** 音频 */
    public static final int FILETYPE_IMAGE = 2;

    /** 图片 */
    public static final int FILETYPE_VIDEO = 3;

    /**
     * 视频  
     * 语音识别语言
     */
    public static final int SPEECHLANG_MANDARIN = 0;

    /** 普通话 */
    public static final int SPEECHLANG_YUEYU = 1;

    /** 粤语 */
    public static final int SPEECHLANG_SICHUAN = 2;

    /** 四川话 */
    public static final int SPEECHLANG_HENAN = 3;

    /** 河南话 */
    public static final int SPEECHLANG_ENGLISH = 4;

    /** 英语 */
    public static final int SPEECHLANG_TRADITIONAL = 5;

    /**
     * 繁体中文
     * 行政区划等级
     */
    public static final int DISTRICTLEVEL_UNKNOW = 0;

    public static final int DISTRICTLEVEL_COUNTRY = 1;

    /** 国家 */
    public static final int DISTRICTLEVEL_PROVINCE = 2;

    /** 省份 */
    public static final int DISTRICTLEVEL_CITY = 3;

    /** 市 */
    public static final int DISTRICTLEVEL_COUNTY = 4;

    /** 区县 */
    public static final int DISTRICTLEVEL_STREET = 5;

    /**
     * 街道
     * 性别
     */
    public static final int SEX_UNKNOWN = 0;

    public static final int SEX_MALE = 1;

    public static final int SEX_FEMALE = 2;

    /** 用户在线状态 */
    public static final int STATUS_ONLINE = 0;

    /** 在线 */
    public static final int STATUS_OFFLINE = 1;

    /** 离线 */
    public static final int STATUS_INVISIBLE = 2;

    /**
     * 隐身
     * 好友添加权限
     */
    public static final int NOT_ALLOW_ADD = 0;

    /** 不允许被添加 */
    public static final int NEED_VALIDATE = 1;

    /** 需要验证 */
    public static final int NO_ADD_PERMISSION = 2;

    /**
     * 允许被添加，不需要验证, 默认值
     *----------------------------errorcode----------------------------
     */
    public static final int YIMERRORCODE_SUCCESS = 0;

    /** 成功 */
    public static final int YIMERRORCODE_ENGINENOTINIT = 1;

    /** 未初始化 */
    public static final int YIMERRORCODE_NOTLOGIN = 2;

    /** 未登录 */
    public static final int YIMERRORCODE_PARAMINVALID = 3;

    /** 参数错误 */
    public static final int YIMERRORCODE_TIMEOUT = 4;

    /** 超时 */
    public static final int YIMERRORCODE_STATUSERROR = 5;

    /** 状态错误 */
    public static final int YIMERRORCODE_SDKINVALID = 6;

    /** SDK验证识别 */
    public static final int YIMERRORCODE_ALREADYLOGIN = 7;

    /** 已经登录 */
    public static final int YIMERRORCODE_SERVERERROR = 8;

    /** 服务器错误 */
    public static final int YIMERRORCODE_NETERROR = 9;

    /** 网络错误 */
    public static final int YIMERRORCODE_LOGINSESSIONERROR = 10;

    /** session错误 */
    public static final int YIMERRORCODE_NOTSTARTUP = 11;

    /** 未启动 */
    public static final int YIMERRORCODE_FILENOTEXIST = 12;

    /** 文件不存在 */
    public static final int YIMERRORCODE_SENDFILEERROR = 13;

    /** 发送文件失败 */
    public static final int YIMERRORCODE_UPLOADFAILED = 14;

    /** 上传失败 */
    public static final int YIMERRORCODE_USERNAMEPASSWORDERROR = 15;

    /** 用户名密码错误	 */
    public static final int YIMERRORCODE_USERSTATUSERROR = 16;

    /** 用户状态错误(无效用户) */
    public static final int YIMERRORCODE_MESSAGETOOLONG = 17;

    /** 消息太长 */
    public static final int YIMERRORCODE_RECEIVERTOOLONG = 18;

    /** 接收方ID过长(检查房间名) */
    public static final int YIMERRORCODE_INVALIDCHATTYPE = 19;

    /** 无效聊天类型(私聊、聊天室) */
    public static final int YIMERRORCODE_INVALIDRECEIVER = 20;

    /** 无效用户ID */
    public static final int YIMERRORCODE_UNKNOWERROR = 21;

    public static final int YIMERRORCODE_INVALIDAPPKEY = 22;

    /** 无效APPKEY */
    public static final int YIMERRORCODE_FORBIDDENSPEAK = 23;

    /** 被禁言 */
    public static final int YIMERRORCODE_CREATEFILEFAILED = 24;

    /** 创建文件失败 */
    public static final int YIMERRORCODE_UNSUPPORTFORMAT = 25;

    /** 不支持的文件格式 */
    public static final int YIMERRORCODE_RECEIVEREMPTY = 26;

    /** 接收方为空 */
    public static final int YIMERRORCODE_ROOMIDTOOLONG = 27;

    /** 房间名太长 */
    public static final int YIMERRORCODE_CONTENTINVALID = 28;

    /** 聊天内容严重非法 */
    public static final int YIMERRORCODE_NOLOCATIONAUTHRIZE = 29;

    /** 未打开定位权限 */
    public static final int YIMERRORCODE_UNKNOWLOCATION = 30;

    /** 未知位置 */
    public static final int YIMERRORCODE_UNSUPPORT = 31;

    /** 不支持该接口 */
    public static final int YIMERRORCODE_NOAUDIODEVICE = 32;

    /** 无音频设备 */
    public static final int YIMERRORCODE_AUDIODRIVER = 33;

    /** 音频驱动问题 */
    public static final int YIMERRORCODE_DEVICESTATUSINVALID = 34;

    /** 设备状态错误 */
    public static final int YIMERRORCODE_RESOLVEFILEERROR = 35;

    /** 文件解析错误 */
    public static final int YIMERRORCODE_READWRITEFILEERROR = 36;

    /** 文件读写错误 */
    public static final int YIMERRORCODE_NOLANGCODE = 37;

    /** 语言编码错误 */
    public static final int YIMERRORCODE_TRANSLATEUNABLE = 38;

    /** 翻译接口不可用 */
    public static final int YIMERRORCODE_SPEECHACCENTINVALID = 39;

    /** 语音识别方言无效 */
    public static final int YIMERRORCODE_SPEECHLANGUAGEINVALID = 40;

    /** 语音识别语言无效 */
    public static final int YIMERRORCODE_HASILLEGALTEXT = 41;

    /** 消息含非法字符 */
    public static final int YIMERRORCODE_ADVERTISEMENTMESSAGE = 42;

    /** 消息涉嫌广告 */
    public static final int YIMERRORCODE_ALREADYBLOCK = 43;

    /** 用户已经被屏蔽 */
    public static final int YIMERRORCODE_NOTBLOCK = 44;

    /** 用户未被屏蔽 */
    public static final int YIMERRORCODE_MESSAGEBLOCKED = 45;

    /** 消息被屏蔽 */
    public static final int YIMERRORCODE_LOCATIONTIMEOUT = 46;

    /** 定位超时 */
    public static final int YIMERRORCODE_NOTJOINROOM = 47;

    /** 未加入该房间 */
    public static final int YIMERRORCODE_LOGINTOKENINVALID = 48;

    /** 登录token错误 */
    public static final int YIMERRORCODE_CREATEDIRECTORYFAILED = 49;

    /** 创建目录失败 */
    public static final int YIMERRORCODE_INITFAILED = 50;

    /** 初始化失败 */
    public static final int YIMERRORCODE_DISCONNECT = 51;

    /** 与服务器断开 */
    public static final int YIMERRORCODE_THESAMEPARAM = 52;

    /** 设置参数相同 */
    public static final int YIMERRORCODE_QUERYUSERINFOFAIL = 53;

    /** 查询用户信息失败 */
    public static final int YIMERRORCODE_SETUSERINFOFAIL = 54;

    /** 设置用户信息失败 */
    public static final int YIMERRORCODE_UPDATEUSERONLINESTATEFAIL = 55;

    /** 更新用户在线状态失败 */
    public static final int YIMERRORCODE_NICKNAMETOOLONG = 56;

    /** 昵称太长(> 64 bytes) */
    public static final int YIMERRORCODE_SIGNATURETOOLONG = 57;

    /** 个性签名太长(> 120 bytes) */
    public static final int YIMERRORCODE_NEEDFRIENDVERIFY = 58;

    /** 需要好友验证信息 */
    public static final int YIMERRORCODE_BEREFUSE = 59;

    /** 添加好友被拒绝 */
    public static final int YIMERRORCODE_HASNOTREGISTERUSERINFO = 60;

    /** 未注册用户信息 */
    public static final int YIMERRORCODE_ALREADYFRIEND = 61;

    /** 已经是好友 */
    public static final int YIMERRORCODE_NOTFRIEND = 62;

    /** 非好友 */
    public static final int YIMERRORCODE_NOTBLACK = 63;

    /** 不在黑名单中 */
    public static final int YIMERRORCODE_PHOTOURLTOOLONG = 64;

    /** 头像url过长(>500 bytes) */
    public static final int YIMERRORCODE_PHOTOSIZETOOLARGE = 65;

    /**
     * 头像太大（>100 kb）
     * 服务错误码
     */
    public static final int YIMERRORCODE_ALREADYFRIENDS = 1000;

    public static final int YIMERRORCODE_LOGININVALID = 1001;

    /** 语音部分错误码 */
    public static final int YIMERRORCODE_PTT_START = 2000;

    public static final int YIMERRORCODE_PTT_FAIL = 2001;

    public static final int YIMERRORCODE_PTT_DOWNLOADFAIL = 2002;

    /** 下载语音失败 */
    public static final int YIMERRORCODE_PTT_GETUPLOADTOKENFAIL = 2003;

    /** 获取token失败 */
    public static final int YIMERRORCODE_PTT_UPLOADFAIL = 2004;

    /** 上传失败 */
    public static final int YIMERRORCODE_PTT_NOTSPEECH = 2005;

    /** 未检测到语音或未开始语音 */
    public static final int YIMERRORCODE_PTT_DEVICESTATUSERROR = 2006;

    /** 音频设备状态错误 */
    public static final int YIMERRORCODE_PTT_ISSPEECHING = 2007;

    /** 正在录音 */
    public static final int YIMERRORCODE_PTT_FILENOTEXIST = 2008;

    /** 文件不存在 */
    public static final int YIMERRORCODE_PTT_REACHMAXDURATION = 2009;

    /** 达到语音最大时长限制 */
    public static final int YIMERRORCODE_PTT_SPEECHTOOSHORT = 2010;

    /** 语音时长太短 */
    public static final int YIMERRORCODE_PTT_STARTAUDIORECORDFAILED = 2011;

    /** 启动录音失败 */
    public static final int YIMERRORCODE_PTT_SPEECHTIMEOUT = 2012;

    /** 音频输入超时 */
    public static final int YIMERRORCODE_PTT_ISPLAYING = 2013;

    /** 正在播放 */
    public static final int YIMERRORCODE_PTT_NOTSTARTPLAY = 2014;

    /** 未开始播放 */
    public static final int YIMERRORCODE_PTT_CANCELPLAY = 2015;

    /** 主动取消播放 */
    public static final int YIMERRORCODE_PTT_NOTSTARTRECORD = 2016;

    /** 未开始语音 */
    public static final int YIMERRORCODE_PTT_NOTINIT = 2017;

    /**  未初始化 */
    public static final int YIMERRORCODE_PTT_INITFAILED = 2018;

    /**  初始化失败 */
    public static final int YIMERRORCODE_PTT_AUTHORIZE = 2019;

    /**  录音权限 */
    public static final int YIMERRORCODE_PTT_STARTRECORDFAILED = 2020;

    /**  启动录音失败 */
    public static final int YIMERRORCODE_PTT_STOPRECORDFAILED = 2021;

    /**  停止录音失败 */
    public static final int YIMERRORCODE_PTT_UNSUPPRTFORMAT = 2022;

    /**  不支持的格式 */
    public static final int YIMERRORCODE_PTT_RESOLVEFILEERROR = 2023;

    /**  解析文件错误 */
    public static final int YIMERRORCODE_PTT_READWRITEFILEERROR = 2024;

    /**  读写文件错误 */
    public static final int YIMERRORCODE_PTT_CONVERTFILEFAILED = 2025;

    /**  文件转换失败 */
    public static final int YIMERRORCODE_PTT_NOAUDIODEVICE = 2026;

    /**  无音频设备 */
    public static final int YIMERRORCODE_PTT_NODRIVER = 2027;

    /**  驱动问题 */
    public static final int YIMERRORCODE_PTT_STARTPLAYFAILED = 2028;

    /**  启动播放失败 */
    public static final int YIMERRORCODE_PTT_STOPPLAYFAILED = 2029;

    /**
     *  停止播放失败
     * -------------------------- NOYY --------------------------
     */
    public static final int YIMERRORCODE_IDENTITYCODEERROR = 3000;

    /**  验证码错误 */
    public static final int YIMERRORCODE_USEREXIST = 3001;

    /**  用户已存在 */
    public static final int YIMERRORCODE_USERNOTEXIST = 3002;

    /**  用户不存在 */
    public static final int YIMERRORCODE_PASSWORDERROR = 3003;

    /**  密码错误 */
    public static final int YIMERRORCODE_NEWOLDPASSSAME = 3004;

    /**  新旧密码相同 */
    public static final int YIMERRORCODE_NOTJOINCHANNEL = 3005;

    /**  未加入频道 */
    public static final int YIMERRORCODE_ALREADYJOINCHANNEL = 3006;

    /**  已加入频道 */
    public static final int YIMERRORCODE_CHANNELMEMBERFULL = 3007;

    /**  频道成员已满 */
    public static final int YIMERRORCODE_MATCHTIMEOUT = 3008;

    /**  匹配超时 */
    public static final int YIMERRORCODE_CHANNELDISABLED = 3009;

    /**  频道不可用 */
    public static final int YIMERRORCODE_NOTCHANNELOWNER = 3009;

    /**
     *  频道不可用
     * -------------------------- NOYY --------------------------
     */
    public static final int YIMERRORCODE_FAIL = 10000;

    /** -------------------------- TALK -------------------------- */
    public static final int YOUME_USER_NONE = 0;

    /** 非法用户 */
    public static final int YOUME_USER_TALKER_FREE = 1;

    /** 自由讲话者 */
    public static final int YOUME_USER_TALKER_ON_DEMAND = 2;

    /** 抢麦 */
    public static final int YOUME_USER_LISTENER = 3;

    /** 听众 */
    public static final int YOUME_USER_COMMANDER = 4;

    /** 指挥 */
    public static final int YOUME_USER_HOST = 5;

    /** 主播 */
    public static final int YOUME_USER_GUSET = 6;

    /**
     * 嘉宾
     * ---------------- errorcode ----------------
     */
    public static final int YOUME_SUCCESS = 0;

    /**
     *成功
     * 参数和状态检查
     */
    public static final int YOUME_ERROR_API_NOT_SUPPORTED = -1;

    /**正在使用的SDK不支持特定的API */
    public static final int YOUME_ERROR_INVALID_PARAM = -2;

    /**传入参数错误 */
    public static final int YOUME_ERROR_ALREADY_INIT = -3;

    /**已经初始化 */
    public static final int YOUME_ERROR_NOT_INIT = -4;

    /**还没有初始化，在调用某函数之前要先调用初始化并且要根据返回值确保初始化成功 */
    public static final int YOUME_ERROR_CHANNEL_EXIST = -5;

    /**要加入的频道已经存在 */
    public static final int YOUME_ERROR_CHANNEL_NOT_EXIST = -6;

    /**对频道进入（检查参数为true时）、退出、讲话、设置白名单、抢麦等接口时频道不存在 */
    public static final int YOUME_ERROR_WRONG_STATE = -7;

    /**状态错误 */
    public static final int YOUME_ERROR_NOT_ALLOWED_MOBILE_NETWROK = -8;

    /**不允许使用移动网络 */
    public static final int YOUME_ERROR_WRONG_CHANNEL_MODE = -9;

    /**在单频道模式下调用了多频道接口，或者反之 */
    public static final int YOUME_ERROR_TOO_MANY_CHANNELS = -10;

    /**同时加入了太多频道 */
    public static final int YOUME_ERROR_TOKEN_ERROR = -11;

    /**传入的token认证错误 */
    public static final int YOUME_ERROR_NOT_IN_CHANNEL = -12;

    /**用户不在该频道 */
    public static final int YOUME_ERROR_BE_KICK = -13;

    /**
     *被踢了，还在禁止时间内，不允许进入房间
     * 内部操作错误
     */
    public static final int YOUME_ERROR_MEMORY_OUT = -100;

    /**内存错误 */
    public static final int YOUME_ERROR_START_FAILED = -101;

    /**启动引擎失败 */
    public static final int YOUME_ERROR_STOP_FAILED = -102;

    /** 停止引擎失败 */
    public static final int YOUME_ERROR_ILLEGAL_SDK = -103;

    /**非法使用SDK */
    public static final int YOUME_ERROR_SERVER_INVALID = -104;

    /**语音服务不可用 */
    public static final int YOUME_ERROR_NETWORK_ERROR = -105;

    /**网络错误 */
    public static final int YOUME_ERROR_SERVER_INTER_ERROR = -106;

    /**服务器内部错误 */
    public static final int YOUME_ERROR_QUERY_RESTAPI_FAIL = -107;

    /**请求RestApi信息失败了 */
    public static final int YOUME_ERROR_USER_ABORT = -108;

    /**用户请求中断当前操作 */
    public static final int YOUME_ERROR_SEND_MESSAGE_FAIL = -109;

    /**
     *发送消息失败
     * 麦克风错误
     */
    public static final int YOUME_ERROR_REC_INIT_FAILED = -201;

    /**录音模块初始化失败 */
    public static final int YOUME_ERROR_REC_NO_PERMISSION = -202;

    /**没有录音权限 */
    public static final int YOUME_ERROR_REC_NO_DATA = -203;

    /**虽然初始化成功，但没有音频数据输出，比如oppo系列手机在录音权限被禁止的时候 */
    public static final int YOUME_ERROR_REC_OTHERS = -204;

    /**其他录音模块的错误 */
    public static final int YOUME_ERROR_REC_PERMISSION_UNDEFINED = -205;

    /**
     *录音权限未确定，iOS显示是否允许录音权限对话框时，返回的是这个错误码
     * 抢麦错误
     */
    public static final int YOUME_ERROR_GRABMIC_FULL = -301;

    /**抢麦失败，人数满 */
    public static final int YOUME_ERROR_GRABMIC_HASEND = -302;

    /**
     *抢麦失败，活动已经结束
     * 连麦错误
     */
    public static final int YOUME_ERROR_INVITEMIC_NOUSER = -401;

    /**连麦失败，用户不存在 */
    public static final int YOUME_ERROR_INVITEMIC_OFFLINE = -402;

    /**连麦失败，用户已离线 */
    public static final int YOUME_ERROR_INVITEMIC_REJECT = -403;

    /**连麦失败，用户拒绝 */
    public static final int YOUME_ERROR_INVITEMIC_TIMEOUT = -404;

    /**
     *连麦失败，两种情况：1.连麦时，对方超时无应答 2.通话中，双方通话时间到
     * 频道白名单错误
     */
    public static final int YOUME_ERROR_WHITE_SOMEUSER_ABNORMAL = -501;

    /**设置白名单部分用户异常：已不在房间 */
    public static final int YOUME_ERROR_UNKNOWN = -1000;

    private final CppProxy mModule;

    public RNYIMCommon(ReactApplicationContext reactContext) {
        super(reactContext);
        mModule = create(ReactDjinni.createReactBridge(reactContext));
    }

    @Override
    public String getName() {
        return "RNYIMCommon";
    }

    @Override
    public Map<String, Object> getConstants() {
        final Map<String, Object> constants = new HashMap<>();
        constants.put("EVENT_LOGIN", EVENT_LOGIN);
        constants.put("EVENT_CHANNEL", EVENT_CHANNEL);
        constants.put("EVENT_USERINFO", EVENT_USERINFO);
        constants.put("EVENT_FRIEND", EVENT_FRIEND);
        constants.put("EVENT_MESSAGE", EVENT_MESSAGE);
        constants.put("EVENT_PLAY", EVENT_PLAY);
        constants.put("EVENT_HISTORYMESSAGE", EVENT_HISTORYMESSAGE);
        constants.put("EVENT_HISTORYMESSAGE_SERVER", EVENT_HISTORYMESSAGE_SERVER);
        constants.put("EVENT_LOCATION", EVENT_LOCATION);
        constants.put("EVENT_NOYYLOGIN", EVENT_NOYYLOGIN);
        constants.put("EVENT_NOYYCHANNEL", EVENT_NOYYCHANNEL);
        constants.put("EVENT_VOICE", EVENT_VOICE);
        constants.put("CMD_LOGIN", CMD_LOGIN);
        constants.put("CMD_LOGOUT", CMD_LOGOUT);
        constants.put("CMD_KICKOFF", CMD_KICKOFF);
        constants.put("CMD_JOIN_ROOM", CMD_JOIN_ROOM);
        constants.put("CMD_LEAVE_ROOM", CMD_LEAVE_ROOM);
        constants.put("CMD_SEND_MESSAGE_STATUS", CMD_SEND_MESSAGE_STATUS);
        constants.put("CMD_STOP_AUDIO_MESSAGE", CMD_STOP_AUDIO_MESSAGE);
        constants.put("CMD_SEND_AUDIO_MESSAGE_STATUS", CMD_SEND_AUDIO_MESSAGE_STATUS);
        constants.put("CMD_CANCEL_AUDIO_MESSAGE", CMD_CANCEL_AUDIO_MESSAGE);
        constants.put("CMD_RECV_MAEESAG_NOTIFY", CMD_RECV_MAEESAG_NOTIFY);
        constants.put("CMD_DOWNLOAD_FILE", CMD_DOWNLOAD_FILE);
        constants.put("CMD_DOWNLOAD_FILEY_BY_URL", CMD_DOWNLOAD_FILEY_BY_URL);
        constants.put("CMD_RECORD_VOLUME_CHANGE", CMD_RECORD_VOLUME_CHANGE);
        constants.put("CMD_TEXT_TANSLATE", CMD_TEXT_TANSLATE);
        constants.put("CMD_RECENT_CONTACTS", CMD_RECENT_CONTACTS);
        constants.put("CMD_PLAY_COMPLETE_NOTIFY", CMD_PLAY_COMPLETE_NOTIFY);
        constants.put("CMD_GET_MICROPHONE_STATUS", CMD_GET_MICROPHONE_STATUS);
        constants.put("CMD_QUERY_USER_INFO", CMD_QUERY_USER_INFO);
        constants.put("CMD_SET_USER_INFO", CMD_SET_USER_INFO);
        constants.put("CMD_SWITCH_USER_STATUS", CMD_SWITCH_USER_STATUS);
        constants.put("CMD_SET_HEAD_IMAGE", CMD_SET_HEAD_IMAGE);
        constants.put("CMD_UNSER_INFO_CHANGE_NOTIFY", CMD_UNSER_INFO_CHANGE_NOTIFY);
        constants.put("CMD_SET_USER_EXTEND_STATUS", CMD_SET_USER_EXTEND_STATUS);
        constants.put("CMD_REQUEST_ADD_FRIEND", CMD_REQUEST_ADD_FRIEND);
        constants.put("CMD_BE_REQUEST_ADD_FRIEND", CMD_BE_REQUEST_ADD_FRIEND);
        constants.put("CMD_BE_ADD_FRIEND", CMD_BE_ADD_FRIEND);
        constants.put("CMD_DEAL_BE_REQUEST_ADD_FRIEND", CMD_DEAL_BE_REQUEST_ADD_FRIEND);
        constants.put("CMD_REQUEST_ADD_FRIEND_RESULT_NOTIFY", CMD_REQUEST_ADD_FRIEND_RESULT_NOTIFY);
        constants.put("CMD_DELETE_FRIEND", CMD_DELETE_FRIEND);
        constants.put("CMD_BE_DELETE_FRIEND_NOTIFY", CMD_BE_DELETE_FRIEND_NOTIFY);
        constants.put("CMD_BLACK_FRIEND", CMD_BLACK_FRIEND);
        constants.put("CMD_QUERY_FRIENDS", CMD_QUERY_FRIENDS);
        constants.put("CMD_QUERY_FRIEND_REQUEST_LIST", CMD_QUERY_FRIEND_REQUEST_LIST);
        constants.put("CMD_GET_RECOMMAND_USER", CMD_GET_RECOMMAND_USER);
        constants.put("CMD_QUERY_LOCAL_HISTORY_MSG", CMD_QUERY_LOCAL_HISTORY_MSG);
        constants.put("CMD_QUERY_ROOM_HISTORY_MSG_SERVER", CMD_QUERY_ROOM_HISTORY_MSG_SERVER);
        constants.put("CMD_LOCATION_UPDATE", CMD_LOCATION_UPDATE);
        constants.put("CMD_LOCATION_GET_NEARBY_OBJECT", CMD_LOCATION_GET_NEARBY_OBJECT);
        constants.put("CMD_LOCATION_GET_DISTANCE", CMD_LOCATION_GET_DISTANCE);
        constants.put("CMD_REGISTE", CMD_REGISTE);
        constants.put("CMD_HXRLOGIN", CMD_HXRLOGIN);
        constants.put("CMD_RESET_PASSWORD", CMD_RESET_PASSWORD);
        constants.put("CMD_UPDATE_PASSWORD", CMD_UPDATE_PASSWORD);
        constants.put("CMD_MOBILEPHONE_IDENTIFYING_CODE", CMD_MOBILEPHONE_IDENTIFYING_CODE);
        constants.put("CMD_CREATE_CHANNEL", CMD_CREATE_CHANNEL);
        constants.put("CMD_INVITE_JOIN_CHANNEL", CMD_INVITE_JOIN_CHANNEL);
        constants.put("CMD_ASKFOR_JOIN_CHANNEL", CMD_ASKFOR_JOIN_CHANNEL);
        constants.put("CMD_LEAVE_CHANNEL", CMD_LEAVE_CHANNEL);
        constants.put("CMD_MATCH_CHANNEL", CMD_MATCH_CHANNEL);
        constants.put("CMD_MATCH_CHANNEL_RESULT_NOTIFY", CMD_MATCH_CHANNEL_RESULT_NOTIFY);
        constants.put("CMD_GET_JOINED_CHANNEL", CMD_GET_JOINED_CHANNEL);
        constants.put("CMD_GET_CHANNEL_MEMBER", CMD_GET_CHANNEL_MEMBER);
        constants.put("CMD_CHANNEL_MEMBER_CHANGE_NOTIFY", CMD_CHANNEL_MEMBER_CHANGE_NOTIFY);
        constants.put("CMD_BE_INVITE_JOIN_CHANNEL", CMD_BE_INVITE_JOIN_CHANNEL);
        constants.put("CMD_SET_CHANNEL_MATCH_SWITCH", CMD_SET_CHANNEL_MATCH_SWITCH);
        constants.put("CMD_KICK_CHANNEL_MEMBER", CMD_KICK_CHANNEL_MEMBER);
        constants.put("CMD_BE_KICK_NOTIFY", CMD_BE_KICK_NOTIFY);
        constants.put("CMD_DEVOLVE_CHANNEL_OWNER", CMD_DEVOLVE_CHANNEL_OWNER);
        constants.put("CMD_BECOM_CHANNEL_OWNER_NOTIFY", CMD_BECOM_CHANNEL_OWNER_NOTIFY);
        constants.put("CMD_FOLLOW_JOIN_CHANNEL", CMD_FOLLOW_JOIN_CHANNEL);
        constants.put("CMD_FOLLOW_JOIN_CHANNEL_REQUEST_NOTIFY", CMD_FOLLOW_JOIN_CHANNEL_REQUEST_NOTIFY);
        constants.put("CMD_VERIFY_FOLLOW_JOIN_CHANNEL", CMD_VERIFY_FOLLOW_JOIN_CHANNEL);
        constants.put("CMD_FOLLOW_JOIN_CHANNEL_RESULT_NOTIFY", CMD_FOLLOW_JOIN_CHANNEL_RESULT_NOTIFY);
        constants.put("CMD_INIT", CMD_INIT);
        constants.put("CMD_JOIN_CHANNEL", CMD_JOIN_CHANNEL);
        constants.put("CMD_LEAVE_ALL_CHANNEL", CMD_LEAVE_ALL_CHANNEL);
        constants.put("CMD_SELF_SPEAKER_CHANGE", CMD_SELF_SPEAKER_CHANGE);
        constants.put("CMD_SELF_MICROPHONE_CHANGE", CMD_SELF_MICROPHONE_CHANGE);
        constants.put("CMD_OTHER_SPEAKER_CHANGE", CMD_OTHER_SPEAKER_CHANGE);
        constants.put("CMD_OTHER_MICROPHONE_CHANGE", CMD_OTHER_MICROPHONE_CHANGE);
        constants.put("CMD_SPEAKER_BE_CHANGE", CMD_SPEAKER_BE_CHANGE);
        constants.put("CMD_MICROPHONE_BE_CHANGE", CMD_MICROPHONE_BE_CHANGE);
        constants.put("CMD_OTHER_SPEECH_CHANGE", CMD_OTHER_SPEECH_CHANGE);
        constants.put("CMD_REST_API", CMD_REST_API);
        constants.put("CMD_MY_MIC_LEVEL", CMD_MY_MIC_LEVEL);
        constants.put("MODEL_FORMAL", MODEL_FORMAL);
        constants.put("MODEL_TEST", MODEL_TEST);
        constants.put("CHATTYPE_PRIVATE", CHATTYPE_PRIVATE);
        constants.put("CHATTYPE_CHANNEL", CHATTYPE_CHANNEL);
        constants.put("MESSAGETYPE_TEXT", MESSAGETYPE_TEXT);
        constants.put("MESSAGETYPE_CUSTOM", MESSAGETYPE_CUSTOM);
        constants.put("MESSAGETYPE_VOICE", MESSAGETYPE_VOICE);
        constants.put("MESSAGETYPE_FILE", MESSAGETYPE_FILE);
        constants.put("FILETYPE_OTHER", FILETYPE_OTHER);
        constants.put("FILETYPE_AUDIO", FILETYPE_AUDIO);
        constants.put("FILETYPE_IMAGE", FILETYPE_IMAGE);
        constants.put("FILETYPE_VIDEO", FILETYPE_VIDEO);
        constants.put("SPEECHLANG_MANDARIN", SPEECHLANG_MANDARIN);
        constants.put("SPEECHLANG_YUEYU", SPEECHLANG_YUEYU);
        constants.put("SPEECHLANG_SICHUAN", SPEECHLANG_SICHUAN);
        constants.put("SPEECHLANG_HENAN", SPEECHLANG_HENAN);
        constants.put("SPEECHLANG_ENGLISH", SPEECHLANG_ENGLISH);
        constants.put("SPEECHLANG_TRADITIONAL", SPEECHLANG_TRADITIONAL);
        constants.put("DISTRICTLEVEL_UNKNOW", DISTRICTLEVEL_UNKNOW);
        constants.put("DISTRICTLEVEL_COUNTRY", DISTRICTLEVEL_COUNTRY);
        constants.put("DISTRICTLEVEL_PROVINCE", DISTRICTLEVEL_PROVINCE);
        constants.put("DISTRICTLEVEL_CITY", DISTRICTLEVEL_CITY);
        constants.put("DISTRICTLEVEL_COUNTY", DISTRICTLEVEL_COUNTY);
        constants.put("DISTRICTLEVEL_STREET", DISTRICTLEVEL_STREET);
        constants.put("SEX_UNKNOWN", SEX_UNKNOWN);
        constants.put("SEX_MALE", SEX_MALE);
        constants.put("SEX_FEMALE", SEX_FEMALE);
        constants.put("STATUS_ONLINE", STATUS_ONLINE);
        constants.put("STATUS_OFFLINE", STATUS_OFFLINE);
        constants.put("STATUS_INVISIBLE", STATUS_INVISIBLE);
        constants.put("NOT_ALLOW_ADD", NOT_ALLOW_ADD);
        constants.put("NEED_VALIDATE", NEED_VALIDATE);
        constants.put("NO_ADD_PERMISSION", NO_ADD_PERMISSION);
        constants.put("YIMERRORCODE_SUCCESS", YIMERRORCODE_SUCCESS);
        constants.put("YIMERRORCODE_ENGINENOTINIT", YIMERRORCODE_ENGINENOTINIT);
        constants.put("YIMERRORCODE_NOTLOGIN", YIMERRORCODE_NOTLOGIN);
        constants.put("YIMERRORCODE_PARAMINVALID", YIMERRORCODE_PARAMINVALID);
        constants.put("YIMERRORCODE_TIMEOUT", YIMERRORCODE_TIMEOUT);
        constants.put("YIMERRORCODE_STATUSERROR", YIMERRORCODE_STATUSERROR);
        constants.put("YIMERRORCODE_SDKINVALID", YIMERRORCODE_SDKINVALID);
        constants.put("YIMERRORCODE_ALREADYLOGIN", YIMERRORCODE_ALREADYLOGIN);
        constants.put("YIMERRORCODE_SERVERERROR", YIMERRORCODE_SERVERERROR);
        constants.put("YIMERRORCODE_NETERROR", YIMERRORCODE_NETERROR);
        constants.put("YIMERRORCODE_LOGINSESSIONERROR", YIMERRORCODE_LOGINSESSIONERROR);
        constants.put("YIMERRORCODE_NOTSTARTUP", YIMERRORCODE_NOTSTARTUP);
        constants.put("YIMERRORCODE_FILENOTEXIST", YIMERRORCODE_FILENOTEXIST);
        constants.put("YIMERRORCODE_SENDFILEERROR", YIMERRORCODE_SENDFILEERROR);
        constants.put("YIMERRORCODE_UPLOADFAILED", YIMERRORCODE_UPLOADFAILED);
        constants.put("YIMERRORCODE_USERNAMEPASSWORDERROR", YIMERRORCODE_USERNAMEPASSWORDERROR);
        constants.put("YIMERRORCODE_USERSTATUSERROR", YIMERRORCODE_USERSTATUSERROR);
        constants.put("YIMERRORCODE_MESSAGETOOLONG", YIMERRORCODE_MESSAGETOOLONG);
        constants.put("YIMERRORCODE_RECEIVERTOOLONG", YIMERRORCODE_RECEIVERTOOLONG);
        constants.put("YIMERRORCODE_INVALIDCHATTYPE", YIMERRORCODE_INVALIDCHATTYPE);
        constants.put("YIMERRORCODE_INVALIDRECEIVER", YIMERRORCODE_INVALIDRECEIVER);
        constants.put("YIMERRORCODE_UNKNOWERROR", YIMERRORCODE_UNKNOWERROR);
        constants.put("YIMERRORCODE_INVALIDAPPKEY", YIMERRORCODE_INVALIDAPPKEY);
        constants.put("YIMERRORCODE_FORBIDDENSPEAK", YIMERRORCODE_FORBIDDENSPEAK);
        constants.put("YIMERRORCODE_CREATEFILEFAILED", YIMERRORCODE_CREATEFILEFAILED);
        constants.put("YIMERRORCODE_UNSUPPORTFORMAT", YIMERRORCODE_UNSUPPORTFORMAT);
        constants.put("YIMERRORCODE_RECEIVEREMPTY", YIMERRORCODE_RECEIVEREMPTY);
        constants.put("YIMERRORCODE_ROOMIDTOOLONG", YIMERRORCODE_ROOMIDTOOLONG);
        constants.put("YIMERRORCODE_CONTENTINVALID", YIMERRORCODE_CONTENTINVALID);
        constants.put("YIMERRORCODE_NOLOCATIONAUTHRIZE", YIMERRORCODE_NOLOCATIONAUTHRIZE);
        constants.put("YIMERRORCODE_UNKNOWLOCATION", YIMERRORCODE_UNKNOWLOCATION);
        constants.put("YIMERRORCODE_UNSUPPORT", YIMERRORCODE_UNSUPPORT);
        constants.put("YIMERRORCODE_NOAUDIODEVICE", YIMERRORCODE_NOAUDIODEVICE);
        constants.put("YIMERRORCODE_AUDIODRIVER", YIMERRORCODE_AUDIODRIVER);
        constants.put("YIMERRORCODE_DEVICESTATUSINVALID", YIMERRORCODE_DEVICESTATUSINVALID);
        constants.put("YIMERRORCODE_RESOLVEFILEERROR", YIMERRORCODE_RESOLVEFILEERROR);
        constants.put("YIMERRORCODE_READWRITEFILEERROR", YIMERRORCODE_READWRITEFILEERROR);
        constants.put("YIMERRORCODE_NOLANGCODE", YIMERRORCODE_NOLANGCODE);
        constants.put("YIMERRORCODE_TRANSLATEUNABLE", YIMERRORCODE_TRANSLATEUNABLE);
        constants.put("YIMERRORCODE_SPEECHACCENTINVALID", YIMERRORCODE_SPEECHACCENTINVALID);
        constants.put("YIMERRORCODE_SPEECHLANGUAGEINVALID", YIMERRORCODE_SPEECHLANGUAGEINVALID);
        constants.put("YIMERRORCODE_HASILLEGALTEXT", YIMERRORCODE_HASILLEGALTEXT);
        constants.put("YIMERRORCODE_ADVERTISEMENTMESSAGE", YIMERRORCODE_ADVERTISEMENTMESSAGE);
        constants.put("YIMERRORCODE_ALREADYBLOCK", YIMERRORCODE_ALREADYBLOCK);
        constants.put("YIMERRORCODE_NOTBLOCK", YIMERRORCODE_NOTBLOCK);
        constants.put("YIMERRORCODE_MESSAGEBLOCKED", YIMERRORCODE_MESSAGEBLOCKED);
        constants.put("YIMERRORCODE_LOCATIONTIMEOUT", YIMERRORCODE_LOCATIONTIMEOUT);
        constants.put("YIMERRORCODE_NOTJOINROOM", YIMERRORCODE_NOTJOINROOM);
        constants.put("YIMERRORCODE_LOGINTOKENINVALID", YIMERRORCODE_LOGINTOKENINVALID);
        constants.put("YIMERRORCODE_CREATEDIRECTORYFAILED", YIMERRORCODE_CREATEDIRECTORYFAILED);
        constants.put("YIMERRORCODE_INITFAILED", YIMERRORCODE_INITFAILED);
        constants.put("YIMERRORCODE_DISCONNECT", YIMERRORCODE_DISCONNECT);
        constants.put("YIMERRORCODE_THESAMEPARAM", YIMERRORCODE_THESAMEPARAM);
        constants.put("YIMERRORCODE_QUERYUSERINFOFAIL", YIMERRORCODE_QUERYUSERINFOFAIL);
        constants.put("YIMERRORCODE_SETUSERINFOFAIL", YIMERRORCODE_SETUSERINFOFAIL);
        constants.put("YIMERRORCODE_UPDATEUSERONLINESTATEFAIL", YIMERRORCODE_UPDATEUSERONLINESTATEFAIL);
        constants.put("YIMERRORCODE_NICKNAMETOOLONG", YIMERRORCODE_NICKNAMETOOLONG);
        constants.put("YIMERRORCODE_SIGNATURETOOLONG", YIMERRORCODE_SIGNATURETOOLONG);
        constants.put("YIMERRORCODE_NEEDFRIENDVERIFY", YIMERRORCODE_NEEDFRIENDVERIFY);
        constants.put("YIMERRORCODE_BEREFUSE", YIMERRORCODE_BEREFUSE);
        constants.put("YIMERRORCODE_HASNOTREGISTERUSERINFO", YIMERRORCODE_HASNOTREGISTERUSERINFO);
        constants.put("YIMERRORCODE_ALREADYFRIEND", YIMERRORCODE_ALREADYFRIEND);
        constants.put("YIMERRORCODE_NOTFRIEND", YIMERRORCODE_NOTFRIEND);
        constants.put("YIMERRORCODE_NOTBLACK", YIMERRORCODE_NOTBLACK);
        constants.put("YIMERRORCODE_PHOTOURLTOOLONG", YIMERRORCODE_PHOTOURLTOOLONG);
        constants.put("YIMERRORCODE_PHOTOSIZETOOLARGE", YIMERRORCODE_PHOTOSIZETOOLARGE);
        constants.put("YIMERRORCODE_ALREADYFRIENDS", YIMERRORCODE_ALREADYFRIENDS);
        constants.put("YIMERRORCODE_LOGININVALID", YIMERRORCODE_LOGININVALID);
        constants.put("YIMERRORCODE_PTT_START", YIMERRORCODE_PTT_START);
        constants.put("YIMERRORCODE_PTT_FAIL", YIMERRORCODE_PTT_FAIL);
        constants.put("YIMERRORCODE_PTT_DOWNLOADFAIL", YIMERRORCODE_PTT_DOWNLOADFAIL);
        constants.put("YIMERRORCODE_PTT_GETUPLOADTOKENFAIL", YIMERRORCODE_PTT_GETUPLOADTOKENFAIL);
        constants.put("YIMERRORCODE_PTT_UPLOADFAIL", YIMERRORCODE_PTT_UPLOADFAIL);
        constants.put("YIMERRORCODE_PTT_NOTSPEECH", YIMERRORCODE_PTT_NOTSPEECH);
        constants.put("YIMERRORCODE_PTT_DEVICESTATUSERROR", YIMERRORCODE_PTT_DEVICESTATUSERROR);
        constants.put("YIMERRORCODE_PTT_ISSPEECHING", YIMERRORCODE_PTT_ISSPEECHING);
        constants.put("YIMERRORCODE_PTT_FILENOTEXIST", YIMERRORCODE_PTT_FILENOTEXIST);
        constants.put("YIMERRORCODE_PTT_REACHMAXDURATION", YIMERRORCODE_PTT_REACHMAXDURATION);
        constants.put("YIMERRORCODE_PTT_SPEECHTOOSHORT", YIMERRORCODE_PTT_SPEECHTOOSHORT);
        constants.put("YIMERRORCODE_PTT_STARTAUDIORECORDFAILED", YIMERRORCODE_PTT_STARTAUDIORECORDFAILED);
        constants.put("YIMERRORCODE_PTT_SPEECHTIMEOUT", YIMERRORCODE_PTT_SPEECHTIMEOUT);
        constants.put("YIMERRORCODE_PTT_ISPLAYING", YIMERRORCODE_PTT_ISPLAYING);
        constants.put("YIMERRORCODE_PTT_NOTSTARTPLAY", YIMERRORCODE_PTT_NOTSTARTPLAY);
        constants.put("YIMERRORCODE_PTT_CANCELPLAY", YIMERRORCODE_PTT_CANCELPLAY);
        constants.put("YIMERRORCODE_PTT_NOTSTARTRECORD", YIMERRORCODE_PTT_NOTSTARTRECORD);
        constants.put("YIMERRORCODE_PTT_NOTINIT", YIMERRORCODE_PTT_NOTINIT);
        constants.put("YIMERRORCODE_PTT_INITFAILED", YIMERRORCODE_PTT_INITFAILED);
        constants.put("YIMERRORCODE_PTT_AUTHORIZE", YIMERRORCODE_PTT_AUTHORIZE);
        constants.put("YIMERRORCODE_PTT_STARTRECORDFAILED", YIMERRORCODE_PTT_STARTRECORDFAILED);
        constants.put("YIMERRORCODE_PTT_STOPRECORDFAILED", YIMERRORCODE_PTT_STOPRECORDFAILED);
        constants.put("YIMERRORCODE_PTT_UNSUPPRTFORMAT", YIMERRORCODE_PTT_UNSUPPRTFORMAT);
        constants.put("YIMERRORCODE_PTT_RESOLVEFILEERROR", YIMERRORCODE_PTT_RESOLVEFILEERROR);
        constants.put("YIMERRORCODE_PTT_READWRITEFILEERROR", YIMERRORCODE_PTT_READWRITEFILEERROR);
        constants.put("YIMERRORCODE_PTT_CONVERTFILEFAILED", YIMERRORCODE_PTT_CONVERTFILEFAILED);
        constants.put("YIMERRORCODE_PTT_NOAUDIODEVICE", YIMERRORCODE_PTT_NOAUDIODEVICE);
        constants.put("YIMERRORCODE_PTT_NODRIVER", YIMERRORCODE_PTT_NODRIVER);
        constants.put("YIMERRORCODE_PTT_STARTPLAYFAILED", YIMERRORCODE_PTT_STARTPLAYFAILED);
        constants.put("YIMERRORCODE_PTT_STOPPLAYFAILED", YIMERRORCODE_PTT_STOPPLAYFAILED);
        constants.put("YIMERRORCODE_IDENTITYCODEERROR", YIMERRORCODE_IDENTITYCODEERROR);
        constants.put("YIMERRORCODE_USEREXIST", YIMERRORCODE_USEREXIST);
        constants.put("YIMERRORCODE_USERNOTEXIST", YIMERRORCODE_USERNOTEXIST);
        constants.put("YIMERRORCODE_PASSWORDERROR", YIMERRORCODE_PASSWORDERROR);
        constants.put("YIMERRORCODE_NEWOLDPASSSAME", YIMERRORCODE_NEWOLDPASSSAME);
        constants.put("YIMERRORCODE_NOTJOINCHANNEL", YIMERRORCODE_NOTJOINCHANNEL);
        constants.put("YIMERRORCODE_ALREADYJOINCHANNEL", YIMERRORCODE_ALREADYJOINCHANNEL);
        constants.put("YIMERRORCODE_CHANNELMEMBERFULL", YIMERRORCODE_CHANNELMEMBERFULL);
        constants.put("YIMERRORCODE_MATCHTIMEOUT", YIMERRORCODE_MATCHTIMEOUT);
        constants.put("YIMERRORCODE_CHANNELDISABLED", YIMERRORCODE_CHANNELDISABLED);
        constants.put("YIMERRORCODE_NOTCHANNELOWNER", YIMERRORCODE_NOTCHANNELOWNER);
        constants.put("YIMERRORCODE_FAIL", YIMERRORCODE_FAIL);
        constants.put("YOUME_USER_NONE", YOUME_USER_NONE);
        constants.put("YOUME_USER_TALKER_FREE", YOUME_USER_TALKER_FREE);
        constants.put("YOUME_USER_TALKER_ON_DEMAND", YOUME_USER_TALKER_ON_DEMAND);
        constants.put("YOUME_USER_LISTENER", YOUME_USER_LISTENER);
        constants.put("YOUME_USER_COMMANDER", YOUME_USER_COMMANDER);
        constants.put("YOUME_USER_HOST", YOUME_USER_HOST);
        constants.put("YOUME_USER_GUSET", YOUME_USER_GUSET);
        constants.put("YOUME_SUCCESS", YOUME_SUCCESS);
        constants.put("YOUME_ERROR_API_NOT_SUPPORTED", YOUME_ERROR_API_NOT_SUPPORTED);
        constants.put("YOUME_ERROR_INVALID_PARAM", YOUME_ERROR_INVALID_PARAM);
        constants.put("YOUME_ERROR_ALREADY_INIT", YOUME_ERROR_ALREADY_INIT);
        constants.put("YOUME_ERROR_NOT_INIT", YOUME_ERROR_NOT_INIT);
        constants.put("YOUME_ERROR_CHANNEL_EXIST", YOUME_ERROR_CHANNEL_EXIST);
        constants.put("YOUME_ERROR_CHANNEL_NOT_EXIST", YOUME_ERROR_CHANNEL_NOT_EXIST);
        constants.put("YOUME_ERROR_WRONG_STATE", YOUME_ERROR_WRONG_STATE);
        constants.put("YOUME_ERROR_NOT_ALLOWED_MOBILE_NETWROK", YOUME_ERROR_NOT_ALLOWED_MOBILE_NETWROK);
        constants.put("YOUME_ERROR_WRONG_CHANNEL_MODE", YOUME_ERROR_WRONG_CHANNEL_MODE);
        constants.put("YOUME_ERROR_TOO_MANY_CHANNELS", YOUME_ERROR_TOO_MANY_CHANNELS);
        constants.put("YOUME_ERROR_TOKEN_ERROR", YOUME_ERROR_TOKEN_ERROR);
        constants.put("YOUME_ERROR_NOT_IN_CHANNEL", YOUME_ERROR_NOT_IN_CHANNEL);
        constants.put("YOUME_ERROR_BE_KICK", YOUME_ERROR_BE_KICK);
        constants.put("YOUME_ERROR_MEMORY_OUT", YOUME_ERROR_MEMORY_OUT);
        constants.put("YOUME_ERROR_START_FAILED", YOUME_ERROR_START_FAILED);
        constants.put("YOUME_ERROR_STOP_FAILED", YOUME_ERROR_STOP_FAILED);
        constants.put("YOUME_ERROR_ILLEGAL_SDK", YOUME_ERROR_ILLEGAL_SDK);
        constants.put("YOUME_ERROR_SERVER_INVALID", YOUME_ERROR_SERVER_INVALID);
        constants.put("YOUME_ERROR_NETWORK_ERROR", YOUME_ERROR_NETWORK_ERROR);
        constants.put("YOUME_ERROR_SERVER_INTER_ERROR", YOUME_ERROR_SERVER_INTER_ERROR);
        constants.put("YOUME_ERROR_QUERY_RESTAPI_FAIL", YOUME_ERROR_QUERY_RESTAPI_FAIL);
        constants.put("YOUME_ERROR_USER_ABORT", YOUME_ERROR_USER_ABORT);
        constants.put("YOUME_ERROR_SEND_MESSAGE_FAIL", YOUME_ERROR_SEND_MESSAGE_FAIL);
        constants.put("YOUME_ERROR_REC_INIT_FAILED", YOUME_ERROR_REC_INIT_FAILED);
        constants.put("YOUME_ERROR_REC_NO_PERMISSION", YOUME_ERROR_REC_NO_PERMISSION);
        constants.put("YOUME_ERROR_REC_NO_DATA", YOUME_ERROR_REC_NO_DATA);
        constants.put("YOUME_ERROR_REC_OTHERS", YOUME_ERROR_REC_OTHERS);
        constants.put("YOUME_ERROR_REC_PERMISSION_UNDEFINED", YOUME_ERROR_REC_PERMISSION_UNDEFINED);
        constants.put("YOUME_ERROR_GRABMIC_FULL", YOUME_ERROR_GRABMIC_FULL);
        constants.put("YOUME_ERROR_GRABMIC_HASEND", YOUME_ERROR_GRABMIC_HASEND);
        constants.put("YOUME_ERROR_INVITEMIC_NOUSER", YOUME_ERROR_INVITEMIC_NOUSER);
        constants.put("YOUME_ERROR_INVITEMIC_OFFLINE", YOUME_ERROR_INVITEMIC_OFFLINE);
        constants.put("YOUME_ERROR_INVITEMIC_REJECT", YOUME_ERROR_INVITEMIC_REJECT);
        constants.put("YOUME_ERROR_INVITEMIC_TIMEOUT", YOUME_ERROR_INVITEMIC_TIMEOUT);
        constants.put("YOUME_ERROR_WHITE_SOMEUSER_ABNORMAL", YOUME_ERROR_WHITE_SOMEUSER_ABNORMAL);
        constants.put("YOUME_ERROR_UNKNOWN", YOUME_ERROR_UNKNOWN);
        return constants;
    }

    private static native CppProxy create(com.youme.reactcpp.ReactBridge bridge);

    private static final class CppProxy
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }
    }
}
