// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from main.djinni

package com.youme.imrn.jni;

import com.facebook.react.bridge.Callback;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.ReadableArray;
import com.facebook.react.bridge.ReadableMap;
import com.facebook.react.bridge.WritableArray;
import com.facebook.react.bridge.WritableMap;
import com.facebook.react.module.annotations.ReactModule;
import com.youme.reactcpp.ReactDjinni;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.atomic.AtomicBoolean;

/**----------------------------频道管理---------------------------- */
@ReactModule(name = "RNYIMChannelManager")
public final class RNYIMChannelManager extends ReactContextBaseJavaModule {
    private final CppProxy mModule;

    public RNYIMChannelManager(ReactApplicationContext reactContext) {
        super(reactContext);
        mModule = create(ReactDjinni.createReactBridge(reactContext));
    }

    @Override
    public String getName() {
        return "RNYIMChannelManager";
    }

    private static native CppProxy create(com.youme.reactcpp.ReactBridge bridge);

    /** 进入IM频道 */
    @ReactMethod
    public void JoinChannel(String channelID, Callback callback) {
        mModule.JoinChannel(channelID, ReactDjinni.wrap(callback));
    }

    /** 离开IM频道 */
    @ReactMethod
    public void LeaveChannel(String channelID, Callback callback) {
        mModule.LeaveChannel(channelID, ReactDjinni.wrap(callback));
    }

    private static final class CppProxy
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        public void JoinChannel(String channelID, com.youme.reactcpp.JavascriptCallback callback)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_JoinChannel(this.nativeRef, channelID, callback);
        }
        private native void native_JoinChannel(long _nativeRef, String channelID, com.youme.reactcpp.JavascriptCallback callback);

        public void LeaveChannel(String channelID, com.youme.reactcpp.JavascriptCallback callback)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_LeaveChannel(this.nativeRef, channelID, callback);
        }
        private native void native_LeaveChannel(long _nativeRef, String channelID, com.youme.reactcpp.JavascriptCallback callback);
    }
}
